.gitattributes
**YouTrack task**: [#ALTAPPS-12](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-12)
**Description**:
- Adds a `.gitattributes` file where files to encrypt should be specified.
=> ALTAPPS-12: git-crypt init

shared/src/commonMain/kotlin/org/hyperskill/app/step/injection/StepFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/presentation/StepActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/presentation/StepFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/presentation/StepReducer.kt
Task: [#ALTAPPS-32](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-32)
- Add `StepFeature`
=> ALTAPPS-32: Steps presentation

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Views/MokoResourcesSampleView.swift, shared/build.gradle.kts
Task: [#ALTAPPS-43](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-43)
**Reviewers**
- Fixes SwiftUI Previews
=> ALTAPPS-43: Fix SwiftUI Previews

androidHyperskillApp/build.gradle.kts, androidHyperskillApp/src/main/AndroidManifest.xml, androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthSocialFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/screen/AuthSocialScreen.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/main/view/ui/activity/MainActivity.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/user_list/injection/UserListComponent.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/user_list/view/ui/activity/MainActivity.kt, androidHyperskillApp/src/main/res/layout/activity_main.xml, gradle/app.versions.toml, gradle/libs.versions.toml
Task: [#ALTAPPS-27](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-27)
**Reviewers**
- setup android navigation based on Cicerone library
=> ALTAPPS-27: Android navigation

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Theme/Color+DesignSystem.swift, iosHyperskillApp/iosHyperskillApp/Theme/ColorPalette.swift
Task: [#ALTAPPS-42](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-42)
- None
**Reviewers**
- Adds colors from shared module `ColorPalette`.
- Adds colors for UI elements `Color+DesignSystem`.
=> ALTAPPS-42: iOS Design System

iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepActionButton.swift, iosHyperskillApp/iosHyperskillApp/Theme/ColorPalette.swift, shared/src/commonMain/resources/MR/colors/colors.xml
Task: [#ALTAPPS-61](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-61)
**Reviewers**
- Update color pallette
=> ALTAPPS-61: remove redundant colors

androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/injection/AuthSocialDataModule.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/injection/AppCoreComponent.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/injection/AppCoreModule.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/main/injection/MainComponent.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/main/injection/MainModule.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/main/presentation/MainViewModel.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/main/view/ui/activity/MainActivity.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/network/injection/AndroidNetworkModule.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthSocial/AuthSocialAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/StepAssembly.swift, shared/src/commonMain/kotlin/org/hyperskill/app/SharedResourcesFormatted.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/data/repository/AuthRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/data/source/AuthRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/domain/interactor/AuthInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/domain/model/UserDeauthorized.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/domain/repository/AuthRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/injection/AuthDataBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/remote/source/AuthRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/remote/source/BearerTokenHttpClientPlugin.kt, shared/src/commonMain/kotlin/org/hyperskill/app/main/injection/AppFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/main/injection/AppFeatureDataBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/main/presentation/AppActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/network/injection/NetworkDataBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/network/injection/NetworkModule.kt
Task: [#ALTAPPS-38](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-38)
**Reviewers**
- Send unauthorized messages from authorized http client
=> ALTAPPS-38: Logout channel

gradle/libs.versions.toml, shared/src/commonMain/kotlin/org/hyperskill/app/auth/remote/source/AuthRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/remote/source/BearerTokenHttpClientPlugin.kt, shared/src/commonMain/kotlin/org/hyperskill/app/login/remote/UserLoginRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/network/injection/NetworkModule.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/remote/StepRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/user_list/remote/UserListRemoteDataSourceImpl.kt
Task: [#ALTAPPS-79](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-79)
**Reviewers**
- Update Ktor to version `2.0.0`
=> ALTAPPS-79: Update ktor

iosHyperskillApp/iosHyperskillApp/Info.plist
Task: [#ALTAPPS-67](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-67)
**Reviewers**
- На айфоне теперь только portrait ориентация
=> ALTAPPS-67: iOS fixed orientation

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/factory/StepQuizFragmentFactory.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_matching/view/adapter/MatchingItemOptionAdapterDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_matching/view/adapter/MatchingItemTitleAdapterDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_matching/view/delegate/MatchingStepQuizFormDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_matching/view/fragment/MatchingStepQuizFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_matching/view/mapper/MatchingItemMapper.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_matching/view/model/MatchingItem.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_theory/view/fragment/StepTheoryFragment.kt, androidHyperskillApp/src/main/res/values/dimens.xml, shared/src/commonMain/kotlin/org/hyperskill/app/step/domain/model/BlockName.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/domain/model/Step.kt, shared/src/commonMain/resources/MR/base/strings.xml
Task: [#ALTAPPS-135](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-135)
**Reviewers**
- Add adapters for title and option
- Add delegate
- Add block name and matching block recognition
=> ALTAPPS-135: Android Matching Problem UI

shared/src/commonMain/kotlin/org/hyperskill/app/profile/data/repository/ProfileRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/data/source/ProfileRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/interactor/ProfileInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/Features.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/Gamification.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/PostedComments.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/Profile.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/TopicsRepetitions.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/repository/ProfileRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/remote/ProfileRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/remote/model/ProfileResponse.kt
Task: [#ALTAPPS-156](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-156)
**Reviewers**
-  Add data / domain / remote layers for current profile info
=> ALTAPPS-156: Current profile info

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_text/view/delegate/TextStepQuizFormDelegate.kt, iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/ChildProtocols/StepQuizChildQuizType.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizString/StepQuizStringAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizString/StepQuizStringDataType.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizString/StepQuizStringView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizString/StepQuizStringViewData.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizString/StepQuizStringViewModel.swift, shared/src/commonMain/resources/MR/base/strings.xml
Task: [#ALTAPPS-154](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-154)
**Reviewers**
- Adds string, number, math quizzes.
=> ALTAPPS-154: iOS string quiz

shared/src/commonMain/kotlin/org/hyperskill/app/profile/remote/ProfileRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/streak/data/repository/StreakRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/streak/data/source/StreakRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/streak/domain/interactor/StreakInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/streak/domain/model/Streak.kt, shared/src/commonMain/kotlin/org/hyperskill/app/streak/domain/repository/StreakRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/streak/remote/StreakRemoteDataSoruceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/streak/remote/StreakRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/streak/remote/model/StreakResponse.kt
Task: [#ALTAPPS-165](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-165)
**Reviewers**
- Add data, domain, remote layers for streak
- Refactor profile with JSON contentType
=> ALTAPPS-165: Streak User Info

shared/src/commonMain/kotlin/org/hyperskill/app/profile/injection/ProfileFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileReducer.kt
Task: [#ALTAPPS-166](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-166)
**Reviewers**
- Add profile feature
- Add reducer and dispatcher
- Add feature builder
=> ALTAPPS-166: Shared Profile Presentation Layer

shared/src/commonMain/kotlin/org/hyperskill/app/track/data/repository/TrackRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/data/source/TrackRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/interactor/TrackInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/model/ProjectsByLevel.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/model/Track.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/repository/TrackRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/remote/TrackRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/remote/model/TrackResponse.kt
Task: [#ALTAPPS-171](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-171)
**Reviewers**
- Add domain, data, remote layers for track information
=> ALTAPPS-171: Shared Track Information

shared/src/commonMain/kotlin/org/hyperskill/app/project/data/repository/ProjectRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project/data/source/ProjectRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project/domain/interactor/ProjectInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project/domain/model/Project.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project/domain/model/Track.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project/domain/repository/ProjectRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project/remote/ProjectRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project/remote/model/ProjectRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project/remote/model/ProjectResponse.kt
Task: [#ALTAPPS-172](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-172)
**Reviewers**
- Add data, domain, remote layers for project
=> ALTAPPS-172: Shared Project Info

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/factory/StepQuizViewStateDelegateFactory.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_choice/view/fragment/ChoiceStepQuizFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_matching/view/delegate/MatchingStepQuizFormDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_matching/view/fragment/MatchingStepQuizFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_sorting/view/fragment/SortingStepQuizFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_table/view/fragment/TableStepQuizFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_text/view/fragment/TextStepQuizFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_step_quiz.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_choice.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_choice_skeleton.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_sorting.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_sorting_skeleton.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_table.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_table_skeleton.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_text.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_text_skeleton.xml
Task: [#ALTAPPS-193](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-193)
**Reviewers**
- Add skeletons for every quiz
=> ALTAPPS-193: Android Skeleton Placeholders

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppNavigation.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppNavigationState.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthCredentials/AuthCredentialsAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthCredentials/AuthCredentialsViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthCredentials/Views/AuthCredentialsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthSocial/AuthOutputProtocol.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthSocial/AuthSocialAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthSocial/AuthSocialViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthSocial/Views/AuthSocialView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/Views/HomeView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/ProfileView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Track/Views/TrackView.swift
**Reviewers**
- Fixes auth navigation
=> iOS: fix auth navigation

androidHyperskillApp/build.gradle.kts, androidHyperskillApp/src/main/AndroidManifest.xml, androidHyperskillApp/src/main/java/org/hyperskill/app/android/HyperskillApp.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/extensions/DateTimeHelper.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/extensions/NotificationChannelInitializer.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/injection/AndroidAppComponent.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/injection/AndroidAppComponentImpl.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/HyperskillNotificationManager.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/HyperskillNotificationManagerImpl.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/MockNotificationDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/NotificationDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/NotificationPublisher.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/NotificationPublisherImpl.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/injection/PlatformNotificationComponent.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/injection/PlatformNotificationComponentImpl.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/model/HyperskillNotificationChannel.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/model/Notification.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/model/NotificationStatuses.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/receiver/AlarmReceiver.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/receiver/BootCompleteReceiver.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/service/BootCompleteService.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/service/NotificationAlarmService.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt, androidHyperskillApp/src/main/res/values/strings.xml, androidHyperskillApp/src/test/java/org/hyperskill/app/android/util/DateTimeHelperTest.kt
Task: [#ALTAPPS-205](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-205)
**Reviewers**
- Add notification system from Stepik
- Replace DI in transfered system
- Add mock notification delegate
=> ALTAPPS-205: Android Notification System

shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheKeyValues.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/repository/NotificationRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/source/NotificationCacheDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/domain/NotificationInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/domain/repository/NotificationRepository.kt
Task: [#ALTAPPS-202](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-202)
- !
**Reviewers**
- Добавлены cache, data, domain слои
=> ALTAPPS-202: shared local notifications / domain

androidHyperskillApp/src/main/java/org/hyperskill/app/android/main/view/ui/activity/MainActivity.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_code/view/delegate/CodeStepQuizFormDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_code/view/fragment/CodeStepQuizFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_step_practice.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_code.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_code_skeleton.xml
Task: [#ALTAPPS-217](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-217)
**Reviewers**
- Move samples in code problem to general step quiz layout
- Add code problem description text
- Update code problem skeleton
=> ALTAPPS-217: Android Problem Design Update

androidHyperskillApp/src/main/java/org/hyperskill/app/android/track/view/fragment/TrackFragment.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/model/StudyPlan.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/model/TrackProgress.kt, shared/src/commonMain/resources/MR/base/strings.xml, shared/src/commonMain/resources/MR/colors/colors.xml
Task: [#ALTAPPS-218](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-218)
**Reviewers**
- Fix competed topic in `TrackProgress`
- Fix track info and progress bar on Android
- Fix color_surface dark color
=> ALTAPPS-218: Shared & Android Track Fixes

shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/repository/NotificationRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/source/NotificationCacheDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/domain/NotificationInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/domain/repository/NotificationRepository.kt
Task: [#ALTAPPS-202](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-202)
- !
**Reviewers**
- Removed unused suspend modifiers
-
=> ALTAPPS-202: remove unused suspend

shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/interactor/StepQuizInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizActionDispatcher.kt
Task: [#ALTAPPS-212](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-212)
**Reviewers**
- Recreate attempts for some types of problems, not for all
=> ALTAPPS-212: Recreate attempts for some problems

shared/src/commonMain/kotlin/org/hyperskill/app/profile/cache/ProfileSettingsCacheDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/cache/ProfileSettingsCacheKeyValues.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/data/repository/ProfileSettingsRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/data/source/ProfileSettingsCacheDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/interactor/ProfileSettingsInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/ProfileSettings.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/Theme.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/repository/ProfileSettingsRepository.kt
Task: [#ALTAPPS-207](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-207)
- !
**Reviewers**
- Добавлен domain слой для настроек профиля
=> ALTAPPS-207: shared profile settings domain

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/extensions/ThemeExtension.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/main/view/ui/activity/MainActivity.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile_settings/view/dialog/ProfileSettingsDialogFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile_settings/view/mapper/ThemeMapper.kt, androidHyperskillApp/src/main/res/drawable/bg_divider_vertical.xml, androidHyperskillApp/src/main/res/layout/fragment_profile.xml, shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/cache/ProfileSettingsCacheDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/data/repository/ProfileSettingsRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/data/source/ProfileSettingsCacheDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/domain/interactor/ProfileSettingsInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/domain/repository/ProfileSettingsRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/injection/ProfileSettingsComponent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/injection/ProfileSettingsComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/presentation/ProfileSettingsActionDispatcher.kt
Task: [#ALTAPPS-236](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-236)
**Reviewers**
- Fix divider theme
- Add ripple effect on settings button in profile
- Save theme, use chosen theme on app start
=> ALTAPPS-236: Android Change App Theme

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/AppDelegate.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/Model/CodeEditorTheme/CodeEditorThemeService.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProfileSettings/ProfileSettingsAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProfileSettings/ProfileSettingsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProfileSettings/ProfileSettingsViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Services/ApplicationTheme/ApplicationTheme+SharedTheme.swift, iosHyperskillApp/iosHyperskillApp/Sources/Services/ApplicationTheme/ApplicationTheme.swift, iosHyperskillApp/iosHyperskillApp/Sources/Services/ApplicationTheme/ApplicationThemeService.swift
Task: [#ALTAPPS-233](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-233)
**Reviewers**
- Sets current theme on launch
- Adds ability to change theme on change in profile settings
=> ALTAPPS-233: iOS change application theme

androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile_settings/view/dialog/ProfileSettingsDialogFragment.kt, androidHyperskillApp/src/main/res/values/styles.xml
Task: [#ALTAPPS-215](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-215)
**Reviewers**
- Add Android Logout Dialog
=> ALTAPPS-215: Android Logout

shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/model/Notification.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/model/NotificationDescription.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/repository/NotificationRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/source/NotificationCacheDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/domain/NotificationInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/domain/repository/NotificationRepository.kt, shared/src/commonMain/resources/MR/base/strings.xml
Task: [#ALTAPPS-235](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-235)
**Reviewers**
- Added real texts of notifications to shared module
=> ALTAPPS-235: shared real notifications texts

iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/Views/HomeDebugStepNavigationView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProblemOfDay/ViewData/ProblemOfDayViewData.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProblemOfDay/ViewData/ProblemOfDayViewDataMapper.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProblemOfDay/Views/ProblemOfDayCardView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProblemOfDay/Views/ProblemOfDayTitle.swift
Task: [#ALTAPPS-240](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-240)
- !
**Reviewers**
- Fixed opening problem of day
-
=> ALTAPPS-240: iOS problem of day card opening fix

shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/streak/domain/model/Streak.kt
Task: [#ALTAPPS-228](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-228)
**Reviewers**
- Fix streak `isNewRecord` after step solved
- Hardly set `ProblemOfDayState.Solved` after problem of the day is solved
=> ALTAPPS-228: Add streak and problem of day fixes

iosHyperskillApp/iosHyperskillApp/Sources/Modules/Track/ViewData/TrackViewDataMapper.swift
Task: [#ALTAPPS-220](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-220)
- !
**Reviewers**
- Fixed current time to complete topic & topic progress
=> ALTAPPS-220: iOS track incorrect information fix

iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProfileSettings/ProfileSettingsView.swift, shared/src/commonMain/resources/MR/base/strings.xml
Task: [#ALTAPPS-241](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-241)
- !
**Reviewers**
- Add account deletion warning dialog
=> ALTAPPS-241: iOS account deletion warning dialog

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_practice/view/fragment/StepPracticeFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_fullscreen_code/dialog/CodeStepQuizFullScreenDialogFragment.kt, iosHyperskillApp/iosHyperskillApp/Sources/Extensions/Shared/StepExtensions.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/ViewData/StepQuizViewDataMapper.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizCode/ViewData/StepQuizCodeViewDataMapper.swift, shared/src/commonMain/kotlin/org/hyperskill/app/extension/TimeFancifier.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/domain/model/Step.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/view/mapper/StepQuizStatsTextMapper.kt, shared/src/commonMain/resources/MR/base/strings.xml, shared/src/commonTest/kotlin/org/hyperskill/TimeFancifierTest.kt
Task: [#ALTAPPS-229](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-229)
**Reviewers**
- Add `TimeFancifier` with tests
- Change hardcoded last step completion time "10 minutes" with time fancifier
=> ALTAPPS-229: Fix Step Latest Completion Time

iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizTableSelectColumns/Views/StepQuizTableSelectColumnsView.swift
Task: [#ALTAPPS-262](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-262)
- !
**Reviewers**
- Aligns title to leading edge
=> ALTAPPS-262: iOS Table problem pan modal align title to leading edge

androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/problem_of_day/view/delegate/ProblemOfDayCardFormDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_home.xml, androidHyperskillApp/src/main/res/layout/layout_quiz_buttons.xml
Task: [#ALTAPPS-252](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-252)
**Reviewers**
- Improve States After Problem Of The Day Is Completed
=> ALTAPPS-252: Android Improve States After Problem Of The Day Is Completed

iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProblemOfDay/Views/ProblemOfDayCardView.swift
Task: [#ALTAPPS-270](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-270)
- !
**Reviewers**
- Uses `BounceButtonStyle`
=> ALTAPPS-270: iOS Problem of the Day Card bounce animation on tap

androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt
Task: [#ALTAPPS-256](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-256)
**Reviewers**
- Add observer to `HomeFragment` to listen for activity `onResume()`
=> ALTAPPS-256: Android Update Home Screen When App goes From Background

androidHyperskillApp/src/main/java/org/hyperskill/app/android/problem_of_day/view/delegate/ProblemOfDayCardFormDelegate.kt, androidHyperskillApp/src/main/res/layout/layout_problem_of_the_day_card.xml
Task: [#ALTAPPS-271](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-271)
**Reviewers**
- Make all the area of problem of the day card clickable
- Add ripple effect on all the area of the card
=> ALTAPPS-271: Make problem of day card clickable with ripple effect

androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthCredentialsFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_profile.xml, androidHyperskillApp/src/main/res/layout/fragment_profile_settings.xml, androidHyperskillApp/src/main/res/layout/fragment_step_practice.xml
Task: [#ALTAPPS-268](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-268), [#ALTAPPS-269](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-269), [#ALTAPPS-282](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-282), [#ALTAPPS-284](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-284)
**Reviewers**
- Hide edit profile button (visibility = invisible)
- Hide "Show discussion" button (visibility = gone)
- Redirect on click on "Reset password" button on auth with email screen
=> ALTAPPS-268: Android Remove Inactive Buttons & Fix Redirect

androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/PlaceholderNewUserFragment.kt, androidHyperskillApp/src/main/res/layout-w380dp/fragment_placeholder_new_user_screen.xml, androidHyperskillApp/src/main/res/layout/fragment_placeholder_new_user_screen.xml, shared/src/commonMain/resources/MR/base/strings.xml
Task: [#ALTAPPS-283](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-283)
**Reviewers**
- Add sign in button and deauthorize on click
- Update texts
=> ALTAPPS-283: Update placeholder screen

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/delegate/StepQuizFeedbackBlocksDelegate.kt, androidHyperskillApp/src/main/res/layout/layout_step_quiz_feedback_block.xml
Task: [#ALTAPPS-267](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-267)
**Reviewers**
- Use LatexView in description block to properly render feedback
=> ALTAPPS-267: Android Use LatexView In Feedback

androidHyperskillApp/src/main/AndroidManifest.xml, androidHyperskillApp/src/main/res/values/strings.xml, iosHyperskillApp/iosHyperskillApp/Info.plist, shared/src/commonMain/resources/MR/base/strings.xml
Task: [#ALTAPPS-259](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-259)
**Reviewers**
- Update strings with app name
- Set Android app name
=> ALTAPPS-259: Update App Name

androidHyperskillApp/src/main/res/layout/fragment_track.xml
Task: [#ALTAPPS-287](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-287)
**Reviewers**
- Fix track screen scrolling by moving track's icon and name inside ScrollView
=> ALTAPPS-287: Android Fix Track Screen Scrolling

iosHyperskillApp/.swiftlint.yml, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/Registration/NotificationsRegistrationService.swift, iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/Views/HomeView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/ProfileViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/StepQuizViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift
Task: [#ALTAPPS-242](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-242)
- !
**Reviewers**
- Use shared module & asking for permissions improvement
-
=> ALTAPPS-242: iOS ask permission after problem of day is solved

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/extensions/NotificationExtensions.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt
Task: [#ALTAPPS-289](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-289)
**Reviewers**
- Add checks to profile daily reminders button and redirect to settings if notifications disabled by user
- Add same checks after solving steps
=> ALTAPPS-289: Android sync system notification enabled with app daily reminders

iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/StepQuizViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/ViewData/StepQuizViewData.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/ViewData/StepQuizViewDataMapper.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift
Task: [#ALTAPPS-290](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-290)
- !
**Reviewers**
- Show feedback with submission hint if it isn't empty
=> ALTAPPS-290: iOS step quiz feedback fix

androidHyperskillApp/src/main/res/layout-w380dp/fragment_placeholder_new_user_screen.xml, androidHyperskillApp/src/main/res/layout/fragment_placeholder_new_user_screen.xml
Task: [#ALTAPPS-305](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-305)
**Reviewers**
- Updates _Sign in_ button's text and style.
=> ALTAPPS-305: Fix Button Sign in has localised text "Войти"

androidHyperskillApp/src/main/res/layout/fragment_profile_settings.xml, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProfileSettings/ProfileSettingsView.swift
Task: [#ALTAPPS-312](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-312)
**Reviewers**
- Hides _Rate this application button_ from settings.
=> ALTAPPS-312: Remove rate this application from settings

shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt
Task: [#ALTAPPS-303](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-303)
- !
**Reviewers**
- Use remote data storage to update problem of day
=> ALTAPPS-303: iOS problem of day updating fix

gradle.properties
=> Remove GITHUB_PERSONAL_ACCESS_TOKEN from project gradle.properties

.github/workflows/feature.yml, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Core/FeatureViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthCredentials/AuthCredentialsViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthSocial/AuthSocialViewModel.swift
Task: [#ALTAPPS-320](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-320)
**Reviewers**
- Fixes crash on social sign in.
=> ALTAPPS-320: iOS fix crash on social sign in on Xcode 14 toolchain

shared/src/commonMain/kotlin/org/hyperskill/app/main/injection/AppFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/main/injection/MainComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/main/presentation/AppActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/main/presentation/AppFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/main/presentation/AppReducer.kt
Task: [#ALTAPPS-301](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-301)
**Reviewers**
- Always navigate unauthorized users to the onboarding screen
=> ALTAPPS-301: shared fix onboarding screen disappearing

androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthCredentialsFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthSocialFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthSocialWebViewFragment.kt, iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Extensions/Shared/KotlinThrowable+AsError.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthCredentials/Views/AuthCredentialsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthSocial/AuthSocialViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthSocial/Views/AuthSocialView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Services/Auth/Social/SDKs/AppleIDSocialAuthSDKProvider.swift, iosHyperskillApp/iosHyperskillApp/Sources/Services/Auth/Social/SDKs/GoogleSocialAuthSDKProvider.swift, iosHyperskillApp/iosHyperskillApp/Sources/Services/Auth/Social/SDKs/SocialAuthSDKProvider.swift, iosHyperskillApp/iosHyperskillApp/Sources/Services/Auth/Social/SocialAuthService.swift, iosHyperskillApp/iosHyperskillApp/Sources/Systems/SentryManager.swift, shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthCredentialsActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthCredentialsFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthCredentialsReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthSocialActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthSocialFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthSocialReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthSocialWebViewFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/auth/presentation/AuthSocialWebViewReducer.kt, shared/src/iosMain/kotlin/org/hyperskill/app/core/error/RethrowThrowable.kt
Task: [#ALTAPPS-323](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-323)
**Reviewers**
- Captures sing in errors
=> ALTAPPS-323: Capture sign in exceptions

androidHyperskillApp/build.gradle.kts, gradle/libs.versions.toml
Task: [#ALTAPPS-329](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-329)
**Reviewers**
- Enables [core library desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring)
=> ALTAPPS-329: Android fix crash NoClassDefFoundError Failed resolution of: Ljava/time/Instant

androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthCredentialsFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthSocialFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/sentry/domain/model/SentryBreadcrumbKeyValues.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthCredentials/AuthCredentialsViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthCredentials/Views/AuthCredentialsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthSocial/AuthSocialViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthSocial/Views/AuthSocialView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Systems/SentryManager.swift, shared/src/commonMain/kotlin/org/hyperskill/app/auth/domain/exception/AuthCredentialsException.kt, shared/src/commonMain/kotlin/org/hyperskill/app/sentry/domain/model/SentryBreadcrumbKeyValues.kt
Task: [#ALTAPPS-323](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-323)
**Reviewers**
- Replaces errors capturing with messages capturing (for better issues investigations)
- Adds `Breadcrumbs` for Android
=> ALTAPPS-323: Capture sign in error messages

androidHyperskillApp/build.gradle.kts, gradle/app.versions.toml, gradle/libs.versions.toml
Task: [#ALTAPPS-329](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-329)
- Fixes crash in Android `NoClassDefFoundError Failed resolution of: Ljava/time/Instant`, [#191](https://github.com/hyperskill/mobile-app/pull/191)
=> Hotfix 1.1.1

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/injection/AndroidAppComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/core/injection/AppGraph.kt, shared/src/commonMain/kotlin/org/hyperskill/app/user_storage/cache/UserStorageCacheDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/user_storage/cache/UserStorageCacheKeyValues.kt, shared/src/commonMain/kotlin/org/hyperskill/app/user_storage/data/repository/UserStorageRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/user_storage/data/source/UserStorageCacheDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/user_storage/data/source/UserStorageRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/user_storage/domain/interactor/UserStorageInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/user_storage/domain/model/UserStorage.kt, shared/src/commonMain/kotlin/org/hyperskill/app/user_storage/domain/repository/UserStorageRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/user_storage/injection/UserStorageComponent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/user_storage/injection/UserStorageComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/user_storage/remote/UserStorageRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/user_storage/remote/model/UserStorageResponse.kt, shared/src/iosMain/kotlin/org/hyperskill/app/core/injection/AppGraphImpl.kt
Task: [#ALTAPPS-313](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-313)
**Reviewers**
- Added user storage component
=> ALTAPPS-313: shared user storage component

.github/dependabot.yml, .github/workflows/label.yml
Task: [#ALTAPPS-380](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-380)
**Reviewers**
- Setups dependency updates via Dependabot
=> ALTAPPS-380: CI/CD setup dependabot

.github/workflows/stale.yml
Task: [#ALTAPPS-381](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-381)
**Reviewers**
- Add [stale action](https://github.com/actions/stale) for marking issues and pull requests that have not had a recent interaction
=> ALTAPPS-381: CI/CD mark issues and pull requests that have not had recent interaction

.github/workflows/unit_testing.yml
Task: [#ALTAPPS-388](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-388)
**Reviewers**
- Fixes unit testing conditions
=> ALTAPPS-388: CI/CD fix unit testing conditions

iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizMatching/StepQuizMatchingViewModel.swift
Task: [#ALTAPPS-387](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-387)
**Reviewers**
- Fixes matching problem reply mapping
=> ALTAPPS-387: iOS fix matching problem mapping

.github/dependabot.yml
Task: [#ALTAPPS-389](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-389)
**Reviewers**
- Updates Android `bundler` package ecosystem
=> ALTAPPS-389: CI/CD Android dependabot update bundler

shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/domain/interactor/StepQuizHintsInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsReducer.kt
Task: [#ALTAPPS-370](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-370)
**Reviewers**
- Added documentation for StepQuizHIntsFeature
- Loading last seen hint to show it
=> ALTAPPS-370: iOS last seen hint fix & step quiz hints feature documentation

iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/StepQuizHintsViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/Views/StepQuizHintsView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/comments/data/repository/CommentsRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/comments/data/source/CommentsRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/comments/domain/interactor/CommentsDataInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/comments/domain/model/Like.kt, shared/src/commonMain/kotlin/org/hyperskill/app/comments/domain/model/Reaction.kt, shared/src/commonMain/kotlin/org/hyperskill/app/comments/domain/repository/CommentsRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/comments/remote/CommentsRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/comments/remote/model/LikesRequest.kt, shared/src/commonMain/kotlin/org/hyperskill/app/comments/remote/model/LikesResponse.kt, shared/src/commonMain/kotlin/org/hyperskill/app/comments/remote/model/ReactionsRequest.kt, shared/src/commonMain/kotlin/org/hyperskill/app/comments/remote/model/ReactionsResponse.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/domain/interactor/StepQuizHintsInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsReducer.kt
Task: [#ALTAPPS-370](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-370)
**Reviewers**
- Fixes report hint
- Fixes react to hint
=> ALTAPPS-370: Shared & iOS fix report hint and reactions

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_theory/view/fragment/StepTheoryFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_step_theory.xml, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepTheoryContentView.swift
Task: [#ALTAPPS-397](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-397)
**Reviewers**
- Hides theory views that not working for Android and iOS
=> ALTAPPS-397: Theory hide unnecessary views

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Extensions/UIKit/UIView/UIView+FindViewOfSpecifiedType.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/HomeViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/Views/HomeView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/ProfileViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/ProfileView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Track/TrackViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Track/Views/TrackView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Views/SwiftUI/PullToRefresh.swift, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/hyperskill/HyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/hyperskill/HyperskillAnalyticTarget.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/domain/analytic/HomeClickedPullToRefreshHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/analytic/ProfileClickedPullToRefreshHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_hints/presentation/StepQuizHintsFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/analytic/TrackClickedPullToRefreshHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/presentation/TrackActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/presentation/TrackFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/presentation/TrackReducer.kt
Task: [#ALTAPPS-311](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-311)
**Reviewers**
- Adds `PullToRefresh` control
- Adds pull-to-refresh to home, track and profile tabs
=> ALTAPPS-311: iOS pull-to-refresh for tabs

iosHyperskillApp/iosHyperskillApp/highlight.css
Task: [#ALTAPPS-337](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-337)
**Reviewers**
- Updates CSS styles for `code`
=> ALTAPPS-337: iOS fix CSS styles for code blocks

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/ContentProcessor/View/SwiftUI/LatexView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/ContentProcessor/View/SwiftUI/SwiftUIProcessedContentView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/sharedSwift/Extensions/StepFeatureStateKsExtensions.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/sharedSwift/Extensions/StepQuizFeatureStateKsExtensions.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/StepViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepTextView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepTheoryContentView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/StepQuizViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizFeedbackView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift
Tasks: [#ALTAPPS-340](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-340), [#ALTAPPS-400](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-400)
**Reviewers**
- Conditionally notify about `Step` and `StepQuiz` feature state change
- Implement `StepQuizFeedbackView` with the use of `UIKit` ([ALTAPPS-340](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-340))
- Implement `StepTextView` with the use of `UIKit` ([ALTAPPS-400](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-400))
=> ALTAPPS-340: iOS fix feedback rendering for problems

iosHyperskillApp/iosHyperskillApp/step.css
Task: [#ALTAPPS-317](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-317)
**Reviewers**
- Adds CSS styles for `alert`
=> ALTAPPS-317: iOS add CSS styles for alerts

androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/track/view/fragment/TrackFragment.kt
**Reviewers**
**Refactor Profile and Track fragments before magicLink feature implementation**
=> ALTAPPS-390: Android refactor Profile and Track fragments

shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/streak/domain/model/Streak.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics_repetitions/presentation/TopicsRepetitionsActionDispatcher.kt
Task: [#ALTAPPS-425](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-425)
**Reviewers**
- Check that solved step is daily problem before increasing streak counter
- Use remote data source to load profile in topics repetitions (for correct recommended topics repetitions count)
=> ALTAPPS-425: shared fix profile streak unnecessary increasing

iosHyperskillApp/iosHyperskillApp/Sources/Helpers/Formatter.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/HomeViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/Views/HomeView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/TopicsRepetitionsAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/TopicsRepetitionsViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/TopicsRepetitionsView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics_repetitions/presentation/TopicsRepetitionsActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics_repetitions/presentation/TopicsRepetitionsFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics_repetitions/presentation/TopicsRepetitionsReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics_repetitions/view/mapper/TopicsRepetitionsViewDataMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics_repetitions/view/model/TopicsRepetitionsViewData.kt, shared/src/commonMain/resources/MR/base/plurals.xml
Task: [#ALTAPPS-412](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-412)
**Reviewers**
- Change label "1 time" -> "once" according to web
- Pass recommendedRepetitionsCount via Initialize message to avoid uneccessary network request
=> ALTAPPS-412: shared topics repetitions fixes

androidHyperskillApp/src/main/res/layout/fragment_home.xml
Task: [#ALTAPPS-435](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-435)
**Reviewers**
- Add scroll ability to the Home screen
=> ALTAPPS-435: Add scroll on the Home screen

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_theory/view/fragment/StepTheoryFragment.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/ViewData/StepViewDataMapper.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Track/Views/TrackProgressBlock/TrackProgressCardView.swift
Task: [#ALTAPPS-431](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-431)
**Reviewers**
- Fix incorrect step reading time on both platforms
=> ALTAPPS-431: shared step incorrect reading time

shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/view/mapper/PlaceholderNewUserViewDataMapper.kt
Task: [#ALTAPPS-437](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-437/iOS-Shared-Track-selection-for-new-users)
**Reviewers**
- Move track tap handling into shared module
=> ALTAPPS-437: update trackTap handling

androidHyperskillApp/src/main/res/menu/main_bottom_navigation.xml
Task: [#ALTAPPS-460](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-460)
**Reviewers**
- Fixes titles for the main bottom navigation view
=> ALTAPPS-460: Android fix main bottom navigation titles

androidHyperskillApp/src/main/assets/css/step.css, iosHyperskillApp/iosHyperskillApp/step.css
Task: [#ALTAPPS-458](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-458)
**Reviewers**
- Hides `video` elements in steps
=> ALTAPPS-458: Android, iOS hide video elements in step theory

.github/PULL_REQUEST_TEMPLATE.md
Task: [#ALTAPPS-461](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-461)
**Reviewers**
- Updates pull request template file
=> ALTAPPS-461: Update pull request template

androidHyperskillApp/src/main/java/org/hyperskill/app/android/main/view/ui/activity/MainActivity.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/DailyStudyReminderNotificationDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/NotificationIntentBuilder.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/injection/PlatformNotificationComponentImpl.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/model/ClickedNotificationData.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/model/HyperskillNotificationChannel.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/model/Notification.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt
Task: [#ALTAPPS-438](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-438/Android-Analytics-for-notifications)
**Reviewers**
- Implement daily notification click logging
-  Implement daily notification show logging
=> ALTAPPS-438: Android analytics for notifications

androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/Views/HomeView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeReducer.kt
[#ALTAPPS-467](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-467)
**Checklist**
=> ALTAPPS-467: hide repetitions card when repetitions statistics total count is zero

.github/workflows/cleanup_pr_caches.yml
[#ALTAPPS-477](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-477)
**Checklist**
- Adds workflow that deletes all the caches created by a branch
=> ALTAPPS-477: CI/CD cleanup all caches created by a branch

androidHyperskillApp/src/main/java/org/hyperskill/app/android/placeholder_new_user/dialog/NewUserTrackDetailsBottomSheet.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/dialog/StreakFreezeDialogFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/dialog/CompletedStepOfTheDayDialogFragment.kt
[#ALTAPPS-470](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-470)
**Checklist**
- Replace BottomSheetDialog.onDismiss callback with BottomSheetDialogFragment.onDismiss to track bottomSheet hidden
=> ALTAPPS-470: Android fix no event sent on bottom sheet dismissed

androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthCredentialsFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/extensions/ContextExtensions.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/view/ui/widget/ExternalLinkWebViewClient.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile_settings/view/dialog/ProfileSettingsDialogFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/track/view/fragment/TrackFragment.kt
[#ALTAPPS-419](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-419)
**Checklist**
- Wrap startActivity call with try/catch
- Add Toast message for user whether exception is happened
=> ALTAPPS-419: Fix Android crash ActivityNotFoundException

shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileReducer.kt
[#ALTAPPS-482](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-482)
**Checklist**
Add emiting to flow after buying streak freeze
=> ALTAPPS-482: shared hypercoins balance not updated

gradle/libs.versions.toml
[#ALTAPPS-330](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-330)
**Checklist**
- Update gms libs in attempt to fix SignInHubActivity crash during auth via Google
=> ALTAPPS-330: Attempt to fix SignInHubActivity crash

androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthSocialWebViewFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/widget/AuthSocialWebViewClient.kt, shared/build.gradle.kts
[#ALTAPPS-334](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-334)
**Checklist**
- Replace unsafe properties access with safe one
=> ALTAPPS-334: Android AuthSocialWebViewFragment crash

iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/Views/HomeSkeletonView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/Views/HomeView.swift
[#ALTAPPS-504](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-504)
**Checklist**
Fix representation of hypercoins in home header
=> ALTAPPS-504: iOS fix home screen ToolbarItemGroup shows only one item

.github/actions/setup-ios/action.yml, .github/workflows/build_caches.yml, .github/workflows/ios_release_deployment.yml
[#ALTAPPS-493](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-493)
**Checklist**
- Adds workflow that builds caches for iOS and Android projects.
=> ALTAPPS-493: CI/CD build caches for default branch

androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt
[#ALTAPPS-318](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-318)
**Checklist**
-Remove redundant profileDailyRemindersSwitchCompat.isChecked assign
=> ALTAPPS-318: Android fix notifications switch extra click needed

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/extensions/NotificationExtensions.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile_settings/view/dialog/ProfileSettingsDialogFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/view/base/ui/extension/SocialNetworksRedirectExtensions.kt
[#ALTAPPS-522](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-522)
**Checklist**
- Refactor notificationChannel availability (reduce duplication)
- Wrap all startActivity call with try/catch
=> ALTAPPS-522: Fix ActivityNotFound crashes

.github/actions/setup-ios/action.yml, .github/labeler.yml
[#ALTAPPS-538](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-538)
**Checklist**
Bumps Xcode version from **14.1** to **14.2**
=> ALTAPPS-538: CI/CD bump Xcode version from 14.1 to 14.2

androidHyperskillApp/src/main/java/org/hyperskill/app/android/problem_of_day/view/delegate/ProblemOfDayCardFormDelegate.kt, androidHyperskillApp/src/main/res/layout/layout_problem_of_the_day_card.xml
[#ALTAPPS-428](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-428)
**Checklist**
=> ALTAPPS-428: add next problem in label on android problem of day card

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/dialog/TopicPracticeCompletedBottomSheet.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/fragment/StepFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/model/StepCompletionHost.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/model/StepCompletionView.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_practice/view/fragment/StepPracticeFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/delegate/StepQuizFormDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_code/view/delegate/CodeStepQuizFormDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_sql/view/delegate/SqlStepQuizFormDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_theory/view/fragment/StepTheoryFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_step_theory.xml, androidHyperskillApp/src/main/res/layout/fragment_topic_practice_completed.xml, androidHyperskillApp/src/main/res/layout/layout_quiz_buttons.xml, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizReducer.kt
[#ALTAPPS-543](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-543/Android-Topic-completion)
**Checklist**
- Implement `StepCompletionFeature` action and messages on Android side
- Features state is propagated via `StepCompletionView` interface. Its direct implementation are `StepTheoryFragment`, `StepPracticeFragment` and `DefaultStepQuizFragment`.
- Message are sent from child fragments via `StepCompletionHost` interface. Its implementation is `StepFragment`.
=> ALTAPPS-543: Android topic completion

shared/src/commonMain/kotlin/org/hyperskill/app/step/data/repository/StepRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/data/source/StepRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/domain/interactor/StepInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/domain/model/StepRoute.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/domain/repository/StepRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/presentation/StepActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/presentation/StepFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/presentation/StepReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/remote/StepRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/interactor/StepQuizInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/repository/SubmissionRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/remote/model/SubmissionRequest.kt
[#ALTAPPS-577](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-577)
**Checklist**
=> ALTAPPS-577: send step view & submission solving context

.github/workflows/android_beta_deployment.yml, .github/workflows/ios_beta_deployment.yml, androidHyperskillApp/src/main/java/org/hyperskill/app/android/code/view/widget/CodeAnalyzer.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/code/view/widget/CodeEditor.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/code/view/widget/CodeEditorLayout.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_code/view/delegate/CodeLayoutDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_code/view/delegate/CodeStepQuizFormDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_code/view/fragment/CodeStepQuizFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_sql/view/delegate/SqlStepQuizFormDelegate.kt
[#ALTAPPS-591](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-591)
**Checklist**
=> ALTAPPS-591: Android fix code editor text resets to empty when opening fullscreen editor

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/view/ui/navigation/MainNavigationContainer.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/view/ui/navigation/NavigationExtensions.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/main/view/ui/navigation/MainScreen.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/fragment/StepFragment.kt
[#ALTAPPS-592](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-592)
**Checklist**
=> ALTAPPS: Android fix back navigation to HomeScreen

iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/ViewData/StepViewData.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/ViewData/StepViewDataMapper.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepHeaderView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepTheoryContentView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/Header/StepQuizNameView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/Header/StepQuizStatsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizStatusView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizCode/StepQuizCodeAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizCode/ViewData/StepQuizCodeViewData.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizCode/ViewData/StepQuizCodeViewDataMapper.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizCode/Views/StepQuizCodeView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizCodeFullScreen/StepQuizCodeFullScreenAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizCodeFullScreen/Views/StepQuizCodeFullScreenDetailsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizCodeFullScreen/Views/StepQuizCodeFullScreenView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSQL/StepQuizSQLAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSQL/StepQuizSQLViewDataMapper.swift
[#ALTAPPS-481](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-481)
**Checklist**
=> ALTAPPS-481: iOS improve problem and theory screen

shared/src/commonMain/kotlin/org/hyperskill/app/profile/injection/ProfileComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/injection/ProfileFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/streaks/domain/model/Streak.kt
[#ALTAPPS-594](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-594)
**Checklist**
Use new fields `can_freeze` and `can_buy_freeze` in Streak model to check freeze state
=> ALTAPPS-594: Shared fix incorrect 1-day streak freeze state

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Extensions/SwiftUI/View/View+MeasureSize.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicToDiscoverNextCard/TopicToDiscoverNextCardView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Track/Views/DiscoverNext/TopicToDiscoverNextButtonView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Track/Views/DiscoverNext/TrackTopicsToDiscoverNextSkeletonListView.swift
[#ALTAPPS-584](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-584)
**Checklist**
Added padding to button
=> ALTAPPS-584: iOS fix topic name doesn't fit to widget size

shared/src/commonMain/kotlin/org/hyperskill/app/step/remote/StepRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/remote/model/ViewsRequest.kt
[#ALTAPPS-577](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-577)
**Checklist**
Use setBody to send /api/views request data
=> ALTAPPS-577: fix /api/views request body

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_practice/view/fragment/StepPracticeFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_fullscreen_code/dialog/CodeStepQuizFullScreenDialogFragment.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/ViewData/StepQuizViewData.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/ViewData/StepQuizViewDataMapper.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/step/domain/model/Step.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/view/mapper/StepQuizStatsTextMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics_repetitions/domain/model/TopicRepetition.kt
[#ALTAPPS-616](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-616)
**Checklist**
- Fixes serialization errors for `Step.last_completed_at` and `TopicRepetition.theory_step`
=> ALTAPPS-616: Fix serialization errors for Step & TopicRepetition

androidHyperskillApp/src/main/java/org/hyperskill/app/android/debug/fragment/DebugFragment.kt, androidHyperskillApp/src/main/res/values/strings.xml
[#ALTAPPS-615](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-615/Android-Switch-environment-not-applied-at-application-restarting)
**Checklist**
=> Fix new backend host is not applied after app restart

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_text/view/delegate/TextStepQuizFormDelegate.kt
[#ALTAPPS-603](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-603)
**Checklist**
=> ALTAPPS-603: Android fix Number step input type

androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthSocialWebViewFragment.kt
[#ALTAPPS-575](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-575)
**Checklist**
=> ALTAPPS-575: Android fix auth via Google in webView

iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/StepViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/Modals/TopicCompletedModalViewController.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/Modals/TopicCompletedModalViewControllerDelegate.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepView.swift, shared/src/commonMain/resources/MR/base/strings.xml
[#ALTAPPS-599](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-599)
**Checklist**
=> ALTAPPS-599: iOS topic completion bottom sheet add continue with next topic button

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/dialog/TopicPracticeCompletedBottomSheet.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/fragment/StepFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_topic_practice_completed.xml
[#ALTAPPS-600](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-600/Android-Topic-completion-bottom-sheet-add-continue-with-next-topic-button)
**Checklist**
=> ALTAPPS-600: Android topic completion continue next topic button

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/injection/AndroidAppComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/core/injection/AppGraph.kt, shared/src/commonMain/kotlin/org/hyperskill/app/learning_activities/data/repository/LearningActivitiesRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/learning_activities/data/source/LearningActivitiesRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/learning_activities/domain/interactor/LearningActivitiesInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/learning_activities/domain/repository/LearningActivitiesRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/learning_activities/remote/LearningActivitiesRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/data/repository/StudyPlanRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/data/source/StudyPlanRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/interactor/StudyPlanInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/model/StudyPlan.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/repository/StudyPlanRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/injection/StudyPlanDataComponent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/injection/StudyPlanDataComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/remote/StudyPlanRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/remote/model/StudyPlanResponse.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics_to_discover_next/domain/interactor/TopicsToDiscoverNextInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics_to_discover_next/injection/TopicsToDiscoverNextDataComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/data/repository/TrackRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/data/source/TrackRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/interactor/TrackInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/repository/TrackRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/injection/TrackComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/injection/TrackFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/presentation/TrackActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/presentation/TrackFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/remote/TrackRemoteDataSourceImpl.kt, shared/src/iosMain/kotlin/org/hyperskill/app/core/injection/AppGraphImpl.kt
[#ALTAPPS-609](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-609)
**Checklist**
=> ALTAPPS-609: Shared add study plan param to learning activities request

shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileReducer.kt
[#ALTAPPS-567](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-567)
**Checklist**
Added synchronization for streak freeze state when hypercoins balance is changed. More details in task [comment](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-567/Shared-1-day-streak-freeze-button-is-visible-at-a-time-while-I-already-have-one-strike-freeze#focus=Comments-74-219184.0-0)
=> ALTAPPS-567: Shared fix streak freeze state synchronization

androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/problem_of_day/view/delegate/ProblemOfDayCardFormDelegate.kt, androidHyperskillApp/src/main/res/layout/layout_problem_of_the_day_card.xml, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/HomeViewModel.swift, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/hyperskill/HyperskillAnalyticTarget.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/domain/analytic/HomeClickedProblemOfDayCardReloadHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/domain/analytic/HomeClickedTopicsRepetitionsCardHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/domain/analytic/HomeHyperskillAnalyticParams.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeReducer.kt
[#ALTAPPS-523](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-523/Android-Add-problem-of-day-refresh-button)
**Checklist**
=> ALTAPPS-523: Android add reloadButton on ProblemOfDayCard

shared/src/commonMain/resources/MR/base/strings.xml
[#ALTAPPS-641](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-641)
**Checklist**
Renames home screen to home
=> ALTAPPS-641: Rename homescreen to home

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/injection/AndroidAppComponentImpl.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/TimeIntervalPickerDialogFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/view/base/ui/extension/TimeIntervalUtil.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/ProfileViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/ViewData/ProfileViewDataMapper.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/ProfileView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/core/injection/AppGraph.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/cache/NotificationCacheKeyValues.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/extension/NotificationExtensions.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/data/flow/DailyStudyRemindersEnabledFlowImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/domain/flow/DailyStudyRemindersEnabledFlow.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/domain/interactor/NotificationInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/injection/NotificationComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/injection/NotificationFlowDataComponent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/injection/NotificationFlowDataComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/analytic/ProfileClickedDailyStudyRemindsToggleHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/injection/ProfileComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/injection/ProfileFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/presentation/ProfileReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/injection/StepQuizComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/injection/StepQuizFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizActionDispatcher.kt, shared/src/commonTest/kotlin/org/hyperskill/HyperskillSentryBreadcrumbAnalyticEventMapperTest.kt, shared/src/iosMain/kotlin/org/hyperskill/app/core/injection/AppGraphImpl.kt
[#ALTAPPS-618](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-618)
**Checklist**
- Added `DailyStudyRemindersEnabledFlow`, use it to sync notification toggle state
- Don't save start interval hour when tap "Cancel" in daily study reminders picker on Android
- Added daily study reminders state to `ProfileFeature`
=> ALTAPPS-618: Shared notifications toggle fix

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/delegate/StepQuizFeedbackBlocksDelegate.kt
[#ALTAPPS-640](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-640)
**Checklist**
=> ALTAPPS-640: Fix evaluation animation on Android

androidHyperskillApp/src/main/res/layout/layout_step_quiz_choice.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_code.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_sorting.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_sql.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_table.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_text.xml
[#ALTAPPS-636](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-636)
**Checklist**
=> ALTAPPS-636: Fix Android stepQuiz layout

shared/src/commonMain/kotlin/org/hyperskill/app/core/domain/repository/InMemoryStateHolder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/core/domain/repository/SingleEntityRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/core/domain/repository/StateHolder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/core/domain/repository/StateRepository.kt
[#ALTAPPS-654](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-654)
**Checklist**
Add SingleEntityRepository abstract class to solve problem of multiple requests and smeared responsibility
=> ALTAPPS-654: Shared implement state repository

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/delegate/StepQuizFeedbackBlocksDelegate.kt
[#ALTAPPS-659](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-659)
**Checklist**
=> ALTAPPS-658: Fix Android stepQuizFeedback visibility

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/injection/AndroidAppComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/core/data/repository/DefaultStateRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/core/domain/repository/StateRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/core/injection/AppGraph.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/Profile.kt, shared/src/commonMain/kotlin/org/hyperskill/app/subscriptions/data/repository/CurrentSubscriptionStateRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/subscriptions/data/source/SubscriptionsRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/subscriptions/domain/model/Subscription.kt, shared/src/commonMain/kotlin/org/hyperskill/app/subscriptions/domain/model/SubscriptionType.kt, shared/src/commonMain/kotlin/org/hyperskill/app/subscriptions/domain/repository/CurrentSubscriptionStateRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/subscriptions/injection/SubscriptionsDataComponent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/subscriptions/injection/SubscriptionsDataComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/subscriptions/remote/SubscriptionsRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/subscriptions/remote/model/SubscriptionsResponse.kt, shared/src/iosMain/kotlin/org/hyperskill/app/core/injection/AppGraphImpl.kt
[#ALTAPPS-654](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-654)
**Checklist**
Added subscriptions data module & refactoring of state repository logic
=> ALTAPPS-654: add subscriptions data module

androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/ProfileView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/Gamification.kt
[#ALTAPPS-646](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-646)
**Checklist**
Use frontend [method](https://github.com/hyperskill/alt/blob/develop/apps/frontend/src/components/UserInfo.vue#L187) to calculate passed tracks count
=> ALTAPPS-646: fix passed tracks count calculation

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/mapper/StepQuizFeedbackMapper.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/ViewData/StepQuizViewDataMapper.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizActionButtons/StepQuizActionButtonState+SubmissionStatus.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/model/submissions/SubmissionStatus.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizResolver.kt
[#ALTAPPS-676](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-676)
**Checklist**
- Adds support for submissions with the status `rejected`.
=> ALTAPPS-676: Shared support rejected submissions

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/view/ui/widget/CompoundLatexItemView.kt
[#ALTAPPS-666](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-666)
**Checklist**
- Remove redundant offset when handling MotionEvent
=> ALTAPPS-666: Android fix choice problems click area

shared/src/commonMain/kotlin/org/hyperskill/app/core/domain/repository_cache/RepositoryCacheProxy.kt, shared/src/commonTest/kotlin/org/hyperskill/RepositoryCacheProxyTest.kt
[#ALTAPPS-679](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-679)
**Checklist**
- Remove CacheProxy sorting
=> ALTAPPS-679: Remove RepositoryCacheProxy sorting

shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StateExtentions.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/view/StudyPlanWidgetViewStateMapper.kt, shared/src/commonTest/kotlin/org/hyperskill/StudyPlanWidgetTest.kt
[#ALTAPPS-702](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-702)
**Checklist**
- Sort sections by StudyPlan.sections
=> ALTAPPS 702: Shared fix sections sorting

androidHyperskillApp/src/main/java/org/hyperskill/app/android/gamification_toolbar/view/ui/delegate/GamificationToolbarDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/gamification_toolbar/view/widget/ToolbarTrackProgressView.kt, androidHyperskillApp/src/main/res/layout/layout_gamification_toolbar.xml
[#ALTAPPS-696](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-696)
**Checklist**
- `ToolbarTrackProgressView` is implemented to show track progress
- Add `ToolbarTrackProgressView` into `GamificationToolbar` layout
- Update `GamificationToolbarDelegate.render`
=> ALTAPPS-696: Android add progress to the toolbar

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Modules/GamificationToolbar/Views/GamificationToolbarContent.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/GamificationToolbar/Views/ProgressBarButtonItem.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/HomeAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Track/TrackAssembly.swift
[#ALTAPPS-698](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-698)
**Checklist**
- Add ProgressBarButtonItem component
- Use StyledHostingController to align title on home and track screens
=> ALTAPPS-698: iOS add progress in gamification toolbar

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/view/ui/adapter/decoration/CustomDividerItemDecoration.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/adapter/StudyPlanItemAnimator.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/delegate/StudyPlanWidgetDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/model/StudyPlanRecyclerItem.kt
[#ALTAPPS-721](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-721)
**Checklist**
- Disable remove & change animation for StudyPlanItemAnimator;
- Declare StudyPlanRecyclerItems as Identifiable to support DiffUtil;
- Fix ItemDecoration with animations.
=> ALTAPPS-721: Android fix StudyPlan list animations

shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetReducer.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/widget/StudyPlanWidgetTest.kt
[#ALTAPPS-743](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-743)
**Checklist**
* **Activity Map Update**
The activity map now replaces older activities with new ones, ensuring an up-to-date view.
=> ALTAPPS-743: Shared fix study plan contains skipped or completed activities

androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/track/view/fragment/TrackFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_home.xml, androidHyperskillApp/src/main/res/layout/fragment_profile.xml, androidHyperskillApp/src/main/res/layout/fragment_track.xml
[#ALTAPPS-706](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-706)
**Checklist**
Move SwipeRefreshLayout from root ViewGroup down to the NestedScrollView root
=> ALTAPPS-706: Fix Android pull-to-refresh

androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/fragment/StudyPlanFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_study_plan.xml
[#ALTAPPS-718](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-718)
**Checklist**
Wrap study-plan's recycler with SwipeRefreshLayout.
=> ALTAPPS-718: Android add SwipeRefreshLayout to StudyPlanFragment

androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/adapter/StudyPlanSectionAdapterDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/delegate/StudyPlanWidgetDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/model/StudyPlanRecyclerItem.kt, androidHyperskillApp/src/main/res/drawable/bg_study_plan_current_badge.xml, androidHyperskillApp/src/main/res/layout/item_study_plan_section.xml, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/view/StudyPlanWidgetViewState.kt
[#ALTAPPS-739](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-739)
**Checklist**
=> ALTAPPS-739: Android Add "Current" badge to study-plan section

androidHyperskillApp/src/main/java/org/hyperskill/app/android/problems_limit/fragment/ProblemsLimitFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/delegate/StudyPlanWidgetDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/fragment/StudyPlanFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_study_plan.xml
[#ALTAPPS-745](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-745)
**Checklist**
- Add ProblemsLimit widget into StudyPlan screen;
- Hide ProblemsLimit root container if its state is Empty;
- Fix StudyPlan last item offset.
=> ALTAPPS-745: Android add problems limit to study plan

shared/src/commonMain/kotlin/org/hyperskill/app/step/domain/model/StepRoute.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizReducer.kt, shared/src/commonTest/kotlin/org/hyperskill/step/domain/model/BlockStub.kt, shared/src/commonTest/kotlin/org/hyperskill/step/domain/model/StepStub.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz/StepQuizTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz/domain/model/AttemptStub.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz/domain/model/SubmissionStub.kt
[#ALTAPPS-747](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-747)
**Checklist**
Fixes a bug when problem of the day and repeating is blocked when problems limit is reached.
=> ALTAPPS-747: Shared fix daily limits blocks learn daily

.github/actions/setup-ios/action.yml, .github/workflows/build.yml, .github/workflows/build_caches.yml, .github/workflows/ios_beta_deployment.yml, .github/workflows/ios_release_deployment.yml, .github/workflows/lint.yml, .github/workflows/unit_testing.yml
[#ALTAPPS-539](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-539), [#ALTAPPS-686](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-686)
**Checklist**
Bumps:
1. macOS version from 12 to 13
2. Xcode version from 14.2 to 14.3
=> ALTAPPS-539, ALTAPPS-686: CI/CD bump macOS and Xcode

iosHyperskillApp/Gemfile, iosHyperskillApp/Gemfile.lock, iosHyperskillApp/Rambafile, iosHyperskillApp/Templates/hyperskill-module/Code/Assembly.swift.liquid, iosHyperskillApp/Templates/hyperskill-module/Code/View.swift.liquid, iosHyperskillApp/Templates/hyperskill-module/Code/ViewModel.swift.liquid, iosHyperskillApp/Templates/hyperskill-module/hyperskill-module.rambaspec
[#ALTAPPS-499](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-499)
**Checklist**
1. Adds [Generamba](https://github.com/strongself/Generamba) code generator to generate iOS modules.
2. Adds `hyperskill-module` template (Assembly + View + ViewModel).
Usage:
```bash
bundle exec generamba gen {MODULE_NAME} hyperskill-module
```
=> ALTAPPS-499: iOS Generamba

androidHyperskillApp/src/main/java/org/hyperskill/app/android/projects_selection/adapter/ProjectAdapterDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/projects_selection/delegate/ProjectSelectionListDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/projects_selection/model/ProjectSelectionRecyclerItem.kt, androidHyperskillApp/src/main/res/layout/item_project.xml, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProjectSelectionList/Model/ProjectSelectionListFeatureViewStateContent+Placeholder.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProjectSelectionList/Views/Grid/Cell/ProjectSelectionListGridCellBadgesView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProjectSelectionList/Views/Grid/Cell/ProjectSelectionListGridCellView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeatureKeys.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/Features.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeaturesMap.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/Profile.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project_selection/presentation/ProjectSelectionListActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project_selection/presentation/ProjectSelectionListFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project_selection/presentation/ProjectSelectionListReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project_selection/presentation/StateExtensions.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project_selection/view/mapper/ProjectSelectionListViewStateMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/projects/domain/model/Project.kt, shared/src/commonMain/kotlin/org/hyperskill/app/projects/domain/model/ProjectProgress.kt, shared/src/commonMain/kotlin/org/hyperskill/app/projects/domain/model/ProjectWithProgress.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/model/ProjectsByLevel.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/model/Track.kt, shared/src/commonTest/kotlin/org/hyperskill/profile/ProfileStub.kt, shared/src/commonTest/kotlin/org/hyperskill/projects_selection/ProjectProgressStub.kt, shared/src/commonTest/kotlin/org/hyperskill/projects_selection/ProjectStub.kt, shared/src/commonTest/kotlin/org/hyperskill/projects_selection/ProjectsListTest.kt, shared/src/commonTest/kotlin/org/hyperskill/track/TrackStub.kt
[#ALTAPPS-770](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-770)
**Checklist**
- Add fetching beta projects for beta users in `ProjectSelectionListActionDispatcher`;
- Implement `sortByScore` extension to sort projects;
- Add `sortedProjectsIds` to the state;
- Add `ProjectListItem.isBeta`;
- Add sorting tests;
- Support `beta` badge on both platforms.
=> ALTAPPS-770: Shared beta projects are not shown in project list

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/injection/AndroidAppComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/comments/remote/CommentsRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/core/injection/AppGraph.kt, shared/src/commonMain/kotlin/org/hyperskill/app/main/domain/interactor/AppInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/main/injection/MainDataComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/network/remote/HttpRequestBuilderExt.kt, shared/src/commonMain/kotlin/org/hyperskill/app/progresses/remote/ProgressesRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/projects/remote/ProjectsRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/providers/cache/ProvidersCacheDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/providers/data/repository/ProvidersRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/providers/data/source/ProvidersCacheDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/providers/data/source/ProvidersRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/providers/domain/interactor/ProvidersInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/providers/domain/model/Provider.kt, shared/src/commonMain/kotlin/org/hyperskill/app/providers/domain/repository/ProvidersRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/providers/injection/ProvidersDataComponent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/providers/injection/ProvidersDataComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/providers/remote/ProvidersRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/providers/remote/model/ProvidersResponse.kt, shared/src/commonMain/kotlin/org/hyperskill/app/stages/remote/StagesRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/remote/StepRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/remote/SubmissionRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/remote/StudyPlanSectionsRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics/remote/TopicsRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/repository/TrackRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/remote/TrackRemoteDataSourceImpl.kt, shared/src/iosMain/kotlin/org/hyperskill/app/core/injection/AppGraphImpl.kt
[#ALTAPPS-779](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-779)
**Checklist**
1. Adds `ProvidersDataComponent`
2. Adds `HttpRequestBuilder.parameterIds` extension function
=> ALTAPPS-779: Shared providers data component

androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthSocialWebViewFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/widget/AuthSocialWebViewClient.kt
[#ALTAPPS-803](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-803)
**Checklist**
- Fix parsing all redirect URLs
=> ALTAPPS-803: Android fix JetBrains authorization 

androidHyperskillApp/src/main/java/org/hyperskill/app/android/gamification_toolbar/view/ui/delegate/GamificationToolbarDelegate.kt
[#ALTAPPS-809](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-809)
**Checklist**
- Replace the value that is set for gems count in the toolbar
=> [Android] Fix gems count value in toolbar

.github/filters.yaml, .github/workflows/detect_changed_files_reusable_workflow.yml, .github/workflows/gh_pages_analytics.yml, shared/src/commonMain/kotlin/org/hyperskill/app/home/domain/analytic/HomeViewedHyperskillAnalyticEvent.kt
[#ALTAPPS-528](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-528)
**Checklist**
1. Conditionally build and deploy analytics documentation on push to develop branch
=> ALTAPPS-528: CI/CD Conditionally build and deploy analytics documentation on push to develop branch

androidHyperskillApp/src/main/java/org/hyperskill/app/android/main/view/ui/activity/MainActivity.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/main/view/ui/fragment/MainFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/main/view/ui/navigation/MainScreen.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/main/view/ui/navigation/MainScreenRouter.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/projects_selection/details/fragment/ProjectSelectionDetailsFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/delegate/StepDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/track_selection/details/fragment/TrackSelectionDetailsFragment.kt
[#ALTAPPS-812](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-812)
**Checklist**
Add `initialTab` parameter to the `MainScreen` to navigate to the predefined tab on creation time.
=> ALTAPPS-812: Android fix navigation to study plan for premium user

iosHyperskillApp/iosHyperskillApp/Sources/Systems/Sentry/SentryManager.swift, shared/src/commonMain/kotlin/org/hyperskill/app/sentry/domain/model/transaction/HyperskillSentryTransactionBuilder.kt
[#ALTAPPS-815](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-815)
**Checklist**
Adds `user.isAuthorized` tag for `app-initialization` transaction
=> ALTAPPS-815: iOS add user.isAuthorized tag for app-initialization transaction

shared/src/commonMain/kotlin/org/hyperskill/app/streaks/domain/model/StreakState.kt
[ALTAPPS-796](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-796)
**Checklist**
Add StreakState.RECOVERED
=> ALTAPPS-796: Shared suport RECOVERED streak state

shared/src/commonMain/kotlin/org/hyperskill/app/main/presentation/AppReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeatureKeys.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeaturesMap.kt, shared/src/commonTest/kotlin/org/hyperskill/main/AppFeatureTest.kt, shared/src/commonTest/kotlin/org/hyperskill/profile/ProfileStub.kt
[#ALTAPPS-832](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-832)
**Checklist**
Deletes `user_streak.recover` feature flag
=> ALTAPPS-832: Shared delete user_streak.recover feature flag

.github/actions/setup-ios/action.yml
[#ALTAPPS-834](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-834)
**Checklist**
- Bumps Xcode version from 14.3 to 14.3.1
=> ALTAPPS-834: CI/CD Bump Xcode version from 14.3 to 14.3.1

shared/src/commonMain/kotlin/org/hyperskill/app/streaks/domain/interactor/StreaksInteractor.kt
[#ALTAPPS-837](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-837)
**Checklist**
Fixes streak recovery cancelation recovers streak
=> ALTAPPS-837: Shared fix streak recovery cancelation recovers streak

iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/NotificationsService.swift, shared/src/commonMain/kotlin/org/hyperskill/app/notification/remote/domain/analytic/PushNotificationClickedHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/remote/domain/analytic/PushNotificationHyperskillAnalyticParams.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/remote/domain/analytic/PushNotificationShownHyperskillAnalyticEvent.kt
[#ALTAPPS-606](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-606), [#ALTAPPS-831](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-831)
**Checklist**
1. `PushNotificationClickedHyperskillAnalyticEvent`
2. `PushNotificationShownHyperskillAnalyticEvent`
3. Logs click event on iOS
=> ALTAPPS-606: Shared analytics for push notifications

.github/actions/setup-ios/action.yml
[#ALTAPPS-833](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-833)
**Checklist**
=> ALTAPPS-833: CI/CD fix iOS build

androidHyperskillApp/build.gradle.kts, gradle/libs.versions.toml
[#ALTAPPS-848](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-848)
**Checklist**
Add sentry android gradle plugin to upload pro-guard mapping to the sentry server to better stack trace reading
=> ALTAPPS-848: Android deobfuscate error stack trace

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/injection/AndroidAppComponentImpl.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/remote/PushNotificationHandler.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/remote/PushNotificationHandlerImpl.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/remote/injection/AndroidPlatformPushNotificationsComponentImpl.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/remote/service/HyperskillFcmService.kt
[#ALTAPPS-840](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-840)
**Checklist**
Log received push notification into analytics
=> ALTAPPS-840: Android analytics for push notifications

iosHyperskillApp/iosHyperskillApp/Sources/AppDelegate.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/NotificationsService.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/ViewControllers/AppViewController.swift, shared/src/commonMain/kotlin/org/hyperskill/app/main/presentation/AppReducer.kt
[#ALTAPPS-839](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-839)
**Checklist**
Adds push notifications routing on iOS
=> ALTAPPS-839: iOS push notifications routing

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/Views/Section/List/Item/StudyPlanSectionItemView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Track/Views/DiscoverNext/TopicToDiscoverNextButtonView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TrackSelection/List/Model/TrackSelectionListFeatureViewStateContent+Placeholder.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TrackSelection/List/Views/Grid/Cell/TrackSelectionListGridCellView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Views/SwiftUI/BackgroundProgressView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/model/TrackWithProgress.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/list/presentation/TrackSelectionListFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/list/view/TrackSelectionListViewStateMapper.kt
[#ALTAPPS-819](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-819)
**Checklist**
Adds progress to the track selection list
=> ALTAPPS-819: iOS track selection list add progress

shared/src/commonMain/kotlin/org/hyperskill/app/projects/domain/model/ProjectWithProgress.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/model/TrackWithProgress.kt, shared/src/commonTest/kotlin/org/hyperskill/ProjectWithProgressTest.kt, shared/src/commonTest/kotlin/org/hyperskill/TrackWithProgressTest.kt, shared/src/commonTest/kotlin/org/hyperskill/projects_selection/ProjectProgressStub.kt, shared/src/commonTest/kotlin/org/hyperskill/projects_selection/ProjectStub.kt, shared/src/commonTest/kotlin/org/hyperskill/projects_selection/ProjectWithProgressStub.kt, shared/src/commonTest/kotlin/org/hyperskill/track/TrackStub.kt, shared/src/commonTest/kotlin/org/hyperskill/track_selection/TrackProgressStub.kt, shared/src/commonTest/kotlin/org/hyperskill/track_selection/TrackWithProgressStub.kt
[#ALTAPPS-681](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-681)
**Checklist**
- Fixed percentages calculation
=> ALTAPPS-681: Shared progress screen fix percentages calculation

iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProjectSelection/List/Model/ProjectSelectionListFeatureViewStateContent+Placeholder.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProjectSelection/List/Views/Grid/Cell/ProjectSelectionListGridCellView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/project_selection/list/presentation/ProjectSelectionListFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project_selection/list/view/mapper/ProjectSelectionListViewStateMapper.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/widget/StudyPlanWidgetTest.kt
[#ALTAPPS-818](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-818)
**Checklist**
- Add progress field to project item in project selection list feature view state
=> ALTAPPS-818: Shared project selection list add progress

androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/adapter/StudyPlanActivityAdapterDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/model/StudyPlanRecyclerItem.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/Views/Section/List/Item/StudyPlanSectionItemView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TrackSelection/List/Views/Grid/Cell/TrackSelectionListGridCellView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Views/SwiftUI/BackgroundProgressView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/learning_activities/domain/model/LearningActivity.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/view/StudyPlanWidgetViewState.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/view/StudyPlanWidgetViewStateMapper.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/widget/StudyPlanWidgetTest.kt
[#ALTAPPS-713](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-713)
**Checklist**
- Implemented `progress` and `formattedProgress` field in `StudyPlanWidgetViewState.SectionItem`
=> ALTAPPS-713: Shared add learning activity widget progress

iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProjectSelection/List/Views/Grid/Cell/ProjectSelectionListGridCellView.swift
[#ALTAPPS-822](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-822)
**Checklist**
Adds progress to the project selection list
=> ALTAPPS-822: iOS project selection list add progress

androidHyperskillApp/src/main/res/layout/view_badge_completed.xml, iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Debug/Views/DebugView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/GamificationToolbar/Views/ProgressBarButtonItem.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProfileSettings/ProfileSettingsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StageImplement/Views/Modals/UnsupportedModal/StageImplementUnsupportedModalView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/Modals/TopicCompletedModalViewController.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/Modals/ProblemOfDaySolvedModalViewController.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/Modals/ProblemsLimitReachedModalViewController.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/Views/StepQuizHintCardView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/Views/StepQuizHintReactionButtonView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/Views/StepQuizHintsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/TopicsRepetitionsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitionsCard/TopicsRepetitionsCardView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Views/SwiftUI/BadgeView/BadgeView+ConcreateTypes.swift, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/Gamification.kt, shared/src/commonMain/kotlin/org/hyperskill/app/progress_screen/injection/ProgressScreenComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/progress_screen/injection/ProgressScreenFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/progress_screen/presentation/ProgressScreenActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/progress_screen/presentation/ProgressScreenFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/progress_screen/presentation/ProgressScreenReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/progress_screen/view/ProgressScreenViewStateMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/model/StudyPlan.kt, shared/src/commonMain/resources/MR/base/strings.xml, shared/src/commonTest/kotlin/org/hyperskill/progress_screen/ProgressScreenTest.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/StudyPlanStub.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/domain/model/StudyPlanStub.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/widget/StudyPlanWidgetTest.kt
[#ALTAPPS-856](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-856)
**Checklist**
- Fixed time to complete in progress screen according frontend realization
=> ALTAPPS-856: shared fix progress screen time to complete

.github/workflows/gh_pages_analytics.yml
[#ALTAPPS-857](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-857)
**Checklist**
Build and deploy analytics documentation only on push to develop branch
=> ALTAPPS-857: CI/CD Build and deploy analytics documentation only on push to develop branch

.github/workflows/build_caches.yml
[#ALTAPPS-858](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-858)
**Checklist**
Conditionally build caches
=> ALTAPPS-858: CI/CD Conditionally build caches

shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/hyperskill/HyperskillAnalyticTarget.kt, shared/src/commonMain/kotlin/org/hyperskill/app/progress_screen/domain/analytic/ProgressScreenClickedChangeProjectHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/progress_screen/domain/analytic/ProgressScreenClickedChangeTrackHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/progress_screen/presentation/ProgressScreenActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/progress_screen/presentation/ProgressScreenFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/progress_screen/presentation/ProgressScreenReducer.kt, shared/src/commonMain/resources/MR/base/strings.xml, shared/src/commonTest/kotlin/org/hyperskill/progress_screen/ProgressScreenTest.kt
[#ALTAPPS-864](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-864)
**Checklist**
- Add messages, action, analytics and strings for changing track and project from project screen
=> ALTAPPS-864: Shared change track and project from progress screen

iosHyperskillApp/iosHyperskillApp/Sources/Extensions/UIKit/UINavigationControllerExtensions.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Routers/StackRouter.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProjectSelection/Details/ProjectSelectionDetailsAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProjectSelection/Details/Views/ProjectSelectionDetailsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TrackSelection/Details/Views/TrackSelectionDetailsView.swift
[#ALTAPPS-876](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-876)
**Checklist**
Fixes navigation
=> ALTAPPS-876: iOS fix track selection screens blocks navigation to home screen

androidHyperskillApp/src/main/java/org/hyperskill/app/android/progress/fragment/ProgressFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/progress/ui/ProgressScreen.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/progress/ui/project/ProjectProgress.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/progress/ui/project/ProjectProgressContent.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/progress/ui/track/TrackProgress.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/progress/ui/track/TrackProgressContent.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProjectSelection/List/ProjectSelectionListAssembly.swift, shared/src/androidMain/kotlin/org/hyperskill/app/progress/presentation/ProgressScreenViewModel.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project_selection/list/injection/ProjectSelectionListParams.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/list/injection/TrackSelectionListParams.kt
[#ALTAPPS-866](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-866)
**Checklist**
- Add `Change track` & `Change project` into progress screen
=> ALTAPPS-866: Android change track & project

androidHyperskillApp/src/debug/java/org/hyperskill/app/android/gamification_toolbar/view/ui/delegate/RouterNavigateToProgressScreen.kt, androidHyperskillApp/src/internalRelease/java/org/hyperskill/app/android/gamification_toolbar/view/ui/delegate/RouterNavigateToProgressScreen.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/gamification_toolbar/view/ui/delegate/GamificationToolbarDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/progress/fragment/ProgressFragment.kt, androidHyperskillApp/src/release/java/org/hyperskill/app/android/gamification_toolbar/view/ui/delegate/RouterNavigateToProgressScreen.kt
[ALTAPPS-875](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-875)
**Checklist**
- Enable navigation to the ProgressFragment for all build flavors
- Remove navigation stubs
=> ALTAPPS-875: Android rollout progress screen to the release app version

androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/widget/AuthSocialWebViewClient.kt
[#ALTAPPS-911](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-911)
**Checklist**
Fix non-mainFrame webView errors were failing the whole authorization flow
=> ALTAPPS-911: Android fix JB authorization

shared/src/commonMain/kotlin/org/hyperskill/app/profile/view/BadgesViewStateMapper.kt
[#ALTAPPS-934](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-934)
**Checklist**
- Fix badges sorting on profile screen
=> ALTAPPS-934: Shared fix badges sorting in profile

androidHyperskillApp/src/main/java/org/hyperskill/app/android/problems_limit/view/ui/delegate/ProblemsLimitDelegate.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProblemsLimit/Views/ProblemsLimitWidgetView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/problems_limit/presentation/ProblemsLimitFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/problems_limit/view/mapper/ProblemsLimitViewStateMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/subscriptions/domain/model/Subscription.kt
[#ALTAPPS-933](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-933)
**Checklist**
- Fix problems limit widget is not visible in case of nullable `Subscription.steps_limit_reset_time` field
=> [Shared] Fix problems limit is not visible

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Extensions/Shared/Model/BadgeRankExtensions.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/NotificationsService.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/ViewControllers/AppViewController.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/Badges/DetailsModal/BadgeDetailsModalView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/Badges/EarnedModal/BadgeEarnedModalView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/Badges/EarnedModal/BadgeEarnedModalViewController.swift, iosHyperskillApp/iosHyperskillApp/Theme/ColorPalette.swift
[#ALTAPPS-893](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-893)
**Checklist**
- Added earned badge modal on iOS
=> ALTAPPS-893: iOS earned badge modal

androidHyperskillApp/src/main/java/org/hyperskill/app/android/main/view/ui/activity/MainActivity.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/click_handling/delegate/NotificationClickHandlingDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/dialog/AbstractBadgeDialogFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/dialog/BadgeDetailsDialogFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/dialog/BadgeDialogFormatter.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/dialog/BadgeEarnedDialogFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_badge_earned.xml
[#ALTAPPS-894](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-894)
**Checklist**
- Added earned badge modal on Android
=> ALTAPPS-894: Android add earned badge bottom sheet

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_hints/delegate/StepQuizHintsDelegate.kt
[#ALTAPPS-943](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-943)
**Checklist**
=> ALTAPPS-943: Android make hint text selectable & add links handling

androidHyperskillApp/src/main/java/org/hyperskill/app/android/code/presentation/highlight/prettify/PrettifyParser.java, androidHyperskillApp/src/main/java/org/hyperskill/app/android/code/presentation/highlight/syntaxhighlight/Parser.java, androidHyperskillApp/src/main/java/org/hyperskill/app/android/code/presentation/highlight/syntaxhighlight/PrettifyParseResult.java, androidHyperskillApp/src/main/java/org/hyperskill/app/android/code/view/CodeSyntaxSpan.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/code/view/ParseResultExtensions.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/code/view/widget/CodeEditor.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_parsons/view/adapter/ParsonsLinesAdapterDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_parsons/view/delegate/ParsonsStepQuizFormDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_parsons/view/mapper/ParsonsLinesMapper.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_parsons/view/model/UiParsonsLine.kt
[#ALTAPPS-966](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-966)
**Checklist**
- Add code highlighting as in the CodeEditor view: refactor the highlighting application to reuse it across application.
- Implement HTML parsing and highlighting cache in the `ParsonsLinesMapper`
=> ALTAPPS-966: Android parsons problems syntax highlighting

androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthSocialWebViewFragment.kt
[#ALTAPPS-978](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-978)
**Checklist**
=> ALTAPPS-978: Android enable localStorage for AuthSocialWebViewClient

androidHyperskillApp/src/main/AndroidManifest.xml
[#ALTAPPS-981](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-981)
**Checklist**
Disable activity recreation on screen orientation change in manifest
=> ALTAPPS-981: Android disable activity recreation on screen orientation change

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Views/SwiftUI/ShineEffect.swift
Adds an effect that highlights the view with a shine moving over the view.
=> iOS shine effect

iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Notifications/NotificationsService.swift, shared/src/commonMain/kotlin/org/hyperskill/app/notification/remote/domain/analytic/PushNotificationClickedHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/remote/domain/analytic/PushNotificationDataAnalyticContextMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/remote/domain/analytic/PushNotificationHyperskillAnalyticParams.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/remote/domain/analytic/PushNotificationShownHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/remote/domain/model/PushNotificationData.kt, shared/src/commonTest/kotlin/org/hyperskill/main/AppFeatureTest.kt, shared/src/commonTest/kotlin/org/hyperskill/notification/NotificationClickHandlingFeatureTest.kt
[#ALTAPPS-984](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-984)
**Checklist**
Adds `notification_id` from push notification payload and logs analytic events with this id
=> ALTAPPS-984: Shared add notification id to notification context

shared/src/commonMain/resources/MR/base/strings.xml, shared/src/commonMain/resources/MR/colors/colors.xml
Adds string and color resources for notifications onboarding
=> Notifications onboarding resources

shared/src/commonMain/kotlin/org/hyperskill/app/notification/local/domain/interactor/NotificationInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notifications_onboarding/presentation/NotificationsOnboardingReducer.kt
[#ALTAPPS-990](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-990)
**Checklist**
Update dailyStudyReminders request conditions
=> ALTAPPS-990: Fix redundant ask to enable dailyReminders

.github/workflows/unit_testing.yml
Turn off `ios-unit-testing` job on push
=> GitHub Actions: Turn off ios-unit-testing job on push

.github/workflows/ios_unit_testing.yml
Adds `ios-unit-testing` cron job that runs at 00:00 UTC every day
=> GitHub Actions: iOS unit testing cron job

.github/workflows/auto_author_assign.yml
Adds workflow that automatically assigns pull request authors
=> GitHub Actions: Automatically assign pull request authors

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StageImplement/StageImplementView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Views/SwiftUI/Introspect/IntrospectScrollView.swift, iosHyperskillApp/iosHyperskillAppTests/IntrospectTests/IntrospectScrollViewTests.swift
[#ALTAPPS-1000](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1000)
**Checklist**
1. Adds `introspectScrollView(customize:)` view modifier
2. Ignore scrolling adjustment for super view scroll views
=> ALTAPPS-1000: iOS fix code editor loses focus on user typing

iosHyperskillApp/NotificationServiceExtension/NotificationService.swift, iosHyperskillApp/autocorrect.sh, iosHyperskillApp/iosHyperskillAppTests/CollectionsTests/LinkedListTests.swift, iosHyperskillApp/iosHyperskillAppTests/CollectionsTests/QueueTests.swift, iosHyperskillApp/iosHyperskillAppTests/ExtensionsTests/URLExtensionsTests.swift, iosHyperskillApp/iosHyperskillAppTests/FrameworksTests/ContentProcessor/HTMLStringTests.swift, iosHyperskillApp/iosHyperskillAppTests/IntrospectTests/IntrospectScrollViewTests.swift, iosHyperskillApp/iosHyperskillAppTests/IntrospectTests/IntrospectTestUtils.swift, iosHyperskillApp/iosHyperskillAppTests/IntrospectTests/IntrospectViewControllerTests.swift, iosHyperskillApp/iosHyperskillAppUITests/LaunchPerformanceTests.swift, iosHyperskillApp/iosHyperskillAppUITests/LaunchTests.swift, iosHyperskillApp/lint.sh
Updates list of paths to the directories of targets to lint and autocorrect
=> iOS: SwiftLint update list of paths to the all targets

.github/workflows/ci.yml, .github/workflows/codeql.yml, iosHyperskillApp/fastlane/Fastfile
[#ALTAPPS-920](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-920)
Sets up GitHub code scanning
=> GitHub Actions: CodeQL code scanning

androidHyperskillApp/src/main/res/layout-night/fragment_onboarding.xml, androidHyperskillApp/src/main/res/layout/fragment_auth_social.xml, androidHyperskillApp/src/main/res/layout/fragment_onboarding.xml, androidHyperskillApp/src/main/res/layout/fragment_profile_settings.xml
[#ALTAPPS-980](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-980)
**Checklist**
=> ALTAPPS-980: Android fix scroll on landscape orientation

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_content_text/view/delegate/TextStepContentDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_code/view/fragment/CodeStepQuizFragment.kt
[ALTAPPS-1009](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1009)
**Checklist**
=> ALTAPPS-1009: Android fix latexView crash

.github/workflows/automerge_into_release.yml
Automerge latest `develop` changes into the current `release` branch
=> GitHub Actions: Automerge develop into release

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_code/view/fragment/CodeStepQuizFragment.kt
[#ALTAPPS-1011](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1011)
**Checklist**
=> ALTAPPS-1011: Android fix input focus invokes keyboard on code editor closing

shared/src/androidMain/kotlin/org/hyperskill/app/step/domain/model/BlockName.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/domain/model/BlockName.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/model/attempts/Component.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/model/submissions/Reply.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/validation/StepQuizReplyValidator.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizResolver.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_fill_blanks/model/FillBlanksConfig.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_fill_blanks/model/FillBlanksData.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_fill_blanks/model/FillBlanksItem.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_fill_blanks/model/InvalidFillBlanksConfigException.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_fill_blanks/presentation/FillBlanksItemMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_fill_blanks/presentation/FillBlanksResolver.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz/FillBlanksMapperTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz/FillBlanksResolverTest.kt, shared/src/iosMain/kotlin/org/hyperskill/app/step/domain/model/BlockName.kt, shared/src/iosMain/kotlin/org/hyperskill/app/step_quiz_fill_blanks/presentation/FillBlanksItemMapperExtensions.kt
[#ALTAPPS-1015](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1015)
**Checklist**
- Add required fields for FillBlanks quiz type.
- Implement `FillBlanksResolver` to check whether data is formatted properly;
- Implement `FillBlanksItemMapper` to map data input list of List<FillBlanksItem> together with language name;
=> ALTAPPS-1015: Shared fill in the blanks with inputs

.github/workflows/automerge_into_release.yml, setup_new_release_branch.sh
Creates new release branch for automerge workflow if needed
=> GitHub Actions: Automerge create new release branch if needed

shared/src/commonMain/kotlin/org/hyperskill/app/freemium/domain/interactor/FreemiumInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/freemium/injection/FreemiumDataComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeatureKeys.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeaturesMap.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/Gamification.kt
[#ALTAPPS-999](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-999)
**Checklist**
- Increase limits after first problem solving when `freemium.increase_limits_for_first_step_completion` feature is enabled
=> ALTAPPS-999: Shared increased limits for first step completion

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_hints/delegate/StepQuizHintsDelegate.kt, androidHyperskillApp/src/main/res/layout/fragment_step_quiz.xml, androidHyperskillApp/src/main/res/values/dimens.xml
[#ALTAPPS-1037](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1037)
**Checklist**
=> ALTAPPS-1037: Fix hint margins in Idle state

androidHyperskillApp/src/main/java/org/hyperskill/app/android/share_streak/fragment/ShareStreakDialogFragment.kt
[#ALTAPPS-1046](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1046)
**Checklist**
=> ALTAPPS-1046: Android fix share streak bottom sheet remains not hidden after any button click

androidHyperskillApp/src/main/java/org/hyperskill/app/android/share_streak/fragment/ShareStreakDialogFragment.kt
[#ALTAPPS-1046](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1046)
**Checklist**
=> ALTAPPS-1046: Android revert share streak auto dismiss

.github/workflows/greetings.yml
1. Reverts 1594d6c3825675961eca0955276534ad563fc25c / #761 
2. Bumps actions/first-interaction to 1.3.0
=> GitHub Actions: Revert temporary delete Greetings workflow

shared/src/commonMain/kotlin/org/hyperskill/app/search/domain/interactor/SearchInteractor.kt
[#ALTAPPS-1057](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1057)
**Checklist**
- Fixes search request
=> ALTAPPS-1057: Shared fix search request calls /api/topics with empty ids

androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/local/DailyStudyReminderLocalNotificationDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/local/HyperskillNotificationManagerImpl.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/local/LocalNotificationDelegate.kt
[ALTAPPS-1073](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1073)
**Checklist**
- Replace exact time scheduling on Android and above with non-exact scheduling;
- Send notification time on rescheduling request
- Don't schedule notifications when time is sent to the server.
=> ALTAPPS-1073: Android fix rescheduling local notification on Android 14

androidHyperskillApp/src/main/res/layout/fragment_profile.xml
[ALTAPPS-1059](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1059)
**Checklist**
- Change gems block position in profile
=> ALTAPPS-1059: Android update gems block position in profile

androidHyperskillApp/src/main/res/layout/fragment_stage_step_wrapper.xml, androidHyperskillApp/src/main/res/layout/fragment_step_practice.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_code_keyboard_extension.xml
[ALTAPPS-1089](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1089)
**Checklist**
- Fix toolbar adding into `ConstaintLayout`
=> ALTAPPS-1089: Android fix codeEditor toolbar visibility

iosHyperskillApp/fastlane/metadata/copyright.txt, iosHyperskillApp/iosHyperskillApp/LaunchScreen.storyboard
- Updates iOS metadata to 2024 year
=> iOS: Update metadata to 2024 year

shared/src/commonMain/kotlin/org/hyperskill/app/core/injection/StateRepositoriesComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/interview_steps/data/repository/InterviewStepsStateRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/interview_steps/data/source/TrackInterviewStepsRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/interview_steps/domain/model/TrackInterviewStep.kt, shared/src/commonMain/kotlin/org/hyperskill/app/interview_steps/remote/TrackInterviewStepsRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/interview_steps/remote/model/TrackInterviewStepsResponse.kt, shared/src/commonMain/kotlin/org/hyperskill/app/network/remote/HttpRequestBuilderExt.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/remote/SubmissionRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/streaks/remote/StreaksRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics_repetitions/remote/TopicsRepetitionsRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/remote/TrackRemoteDataSourceImpl.kt
[#ALTAPPS-1092](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1092)
**Checklist**
- Adds `/api/track-interview-steps` support
=> ALTAPPS-1092: Shared interview preparation /api/track-interview-steps

shared/src/commonMain/kotlin/org/hyperskill/app/interview_preparation/injection/InterviewPreparationWidgetComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/interview_preparation/presentation/InterviewPreparationWidgetActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/interview_preparation/presentation/InterviewPreparationWidgetFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/interview_preparation/presentation/InterviewPreparationWidgetReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeatureKeys.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeaturesMap.kt
[#ALTAPPS-1092](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1092)
**Checklist**
- Adds `isMobileInterviewPreparationEnabled` feature flag
=> ALTAPPS-1092: Shared isMobileInterviewPreparationEnabled feature flag

iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthCredentials/Views/AuthCredentialsFormView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthCredentials/Views/AuthCredentialsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthSocial/Views/AuthSocialControlsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/FirstProblemOnboarding/Views/FirstProblemOnboardingContentView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/NotificationsOnboarding/Views/NotificationsOnboardingContentView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StageImplement/Modals/ProjectCompleted/StageImplementProjectCompletedModalView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StageImplement/Modals/StageCompleted/StageImplementStageCompletedModalView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Welcome/WelcomeView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Views/SwiftUI/Styles/Buttons/RoundedRectangleButtonStyle.swift
- Updates `primary` button style to Apple's design
=> iOS: New CTA button (Apple's style)

shared/src/commonMain/kotlin/org/hyperskill/app/products/data/repository/ProductsRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/products/remote/ProductsRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/products/remote/model/GetProductsRequest.kt
[#ALTAPPS-1076](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1076)
**Checklist**
- Make a request to the API Products with the filter `type=streak freeze`
=> ALTAPPS-1076: Shared use type for filtering streak freeze product

androidHyperskillApp/src/main/java/org/hyperskill/app/android/streak_recovery/view/delegate/StreakRecoveryViewActionDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/streak_recovery/view/fragment/StreakRecoveryDialogFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_streak_recovery.xml, shared/src/commonMain/kotlin/org/hyperskill/app/streak_recovery/presentation/StreakRecoveryFeature.kt
[ALTAPPS-1107](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1107)
**Checklist**
- Add first streak recovery UI
=> ALTAPPS-1107: Android add a state for the first streak recovery

androidHyperskillApp/src/main/AndroidManifest.xml, androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthSocialFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_welcome.xml, androidHyperskillApp/src/main/res/values/strings.xml, iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift, shared/build.gradle.kts, shared/src/androidMain/kotlin/org/hyperskill/app/core/domain/platform/Platform.kt, shared/src/commonMain/kotlin/org/hyperskill/app/core/domain/platform/Platform.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/presentation/ProfileSettingsActionDispatcher.kt, shared/src/commonMain/resources/MR/base/strings.xml, shared/src/iosMain/kotlin/org/hyperskill/app/core/domain/platform/Platform.kt
[ALTAPPS-1112](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1112)
**Checklist**
- Add app name to the common resources;
- Rename the Android app.
=> ALTAPPS-1112: Android change app name

.github/actions/setup-ios/action.yml
- Bumps Xcode version from 15.1 to 15.2
=> GitHub Actions: Bump Xcode version from 15.1 to 15.2

.github/actions/setup-android/action.yml, .github/actions/setup-ios/action.yml
- Bumps actions/setup-java from 3.10.0 to 4.0.0
=> GitHub Actions: Bump actions/setup-java from 3.10.0 to 4.0.0

.editorconfig, .github/workflows/android_beta_deployment.yml, .github/workflows/android_deploy_to_firebase.yml, .github/workflows/android_deploy_to_firebase_manually.yml
- Adds ability to manually deploy Android to Firebase App Distribution
=> GitHub Actions: Deploy Android manually to Firebase App Distribution

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProfileSettings/Views/ProfileSettingsSubscriptionSectionView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProfileSettings/Views/ProfileSettingsView.swift
[#ALTAPPS-1126](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1126)
**Checklist**
- Adds subscription section UI in the profile settings
=> ALTAPPS-1126: iOS subscription info UI profile settings

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Modules/SubscriptionDetails/SubscriptionDetailsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Views/SwiftUI/BadgeView/BadgeView.swift
[#ALTAPPS-1132](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1132)
**Checklist**
- Adds manage subscription UI
=> ALTAPPS-1132: iOS manage subscription UI

shared/src/commonMain/kotlin/org/hyperskill/app/main/injection/AppFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/main/injection/MainComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/click_handling/injection/NotificationClickHandlingComponent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/click_handling/injection/NotificationClickHandlingComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/click_handling/presentation/NotificationClickHandlingActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/click_handling/presentation/NotificationClickHandlingFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notification/click_handling/presentation/NotificationClickHandlingReducer.kt
[#ALTAPPS-1127](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1127)
**Checklist**
- On click `PushNotificationType.DAILY_REMINDER` navigate to next learning activity
=> ALTAPPS-1127: Shared open next learning activity after notification click

androidHyperskillApp/src/main/java/org/hyperskill/app/android/paywall/fragment/PaywallFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/problems_limit/dialog/ProblemsLimitReachedBottomSheet.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_problems_limit_reached.xml, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, shared/src/androidUnitTest/kotlin/org/hyperskill/step_quiz/AndroidStepQuizTest.kt, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/hyperskill/HyperskillAnalyticTarget.kt, shared/src/commonMain/kotlin/org/hyperskill/app/freemium/domain/interactor/FreemiumInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/domain/model/PaywallTransitionSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/analytic/ProblemsLimitReachedModalClickedUnlockUnlimitedProblemsHSAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/injection/StepQuizComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/injection/StepQuizFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizReducer.kt, shared/src/commonMain/resources/MR/base/strings.xml, shared/src/commonTest/kotlin/org/hyperskill/step_quiz/StepQuizTest.kt
[ALTAPPS-1120](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1120)
**Checklist**
- Add `isPaywallFeatureEnabled` field to `StepQuizFeature.Message.FetchAttemptSuccess`
- Refactor `StepQuizFeature.Action.FetchAttempt` handling in `StepQuizActionDispatcher`
- Update `ProblemsLimitReachedBottomSheet` UI.
=> ALTAPPS-1120: Shared, Android add paywall link to limits bottomsheet

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Extensions/SwiftUI/View/View+SafeAreaInset.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProjectSelection/Details/Views/Content/ProjectSelectionDetailsContentView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProjectSelection/Details/Views/Skeleton/ProjectSelectionDetailsSkeletonView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizFillBlanksSelectOptions/Views/UIKit/StepQuizFillBlanksSelectOptionsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TrackSelection/Details/Views/Content/TrackSelectionDetailsContentView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TrackSelection/Details/Views/Skeleton/TrackSelectionDetailsSkeletonView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Views/SwiftUI/Wrappers/TransparentBlurView.swift
=> iOS: Polish up footer views

androidHyperskillApp/src/main/java/org/hyperskill/app/android/problems_limit/view/ui/delegate/ProblemsLimitDelegate.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProblemsLimit/Views/ProblemsLimitWidgetView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/StudyPlanViewModel.swift, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/hyperskill/HyperskillAnalyticPart.kt, shared/src/commonMain/kotlin/org/hyperskill/app/problems_limit/domain/analytic/ProblemsLimitClickedRetryContentLoadingHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/problems_limit/domain/model/ProblemsLimitScreen.kt, shared/src/commonMain/kotlin/org/hyperskill/app/problems_limit/injection/ProblemsLimitComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/problems_limit/presentation/ProblemsLimitActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/problems_limit/presentation/ProblemsLimitFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/problems_limit/presentation/ProblemsLimitReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/screen/presentation/StudyPlanScreenFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/screen/presentation/StudyPlanScreenReducer.kt
[#ALTAPPS-1087](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1087)
**Checklist**
- Fixes a bug with pull-to-refresh on study plan not refreshes problems limit widget
=> ALTAPPS-1087: Shared add Pull-to-refresh for problems limit widget on study plan

iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/ViewControllers/AppViewController.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/HomeViewModel.swift
[#ALTAPPS-1130](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1130)
**Checklist**
- Shows paywall every third time the app is opened
=> ALTAPPS-1130: iOS show paywall every third time

androidHyperskillApp/src/main/java/org/hyperskill/app/android/paywall/fragment/PaywallFragment.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/PaywallFooterView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/PaywallView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/hyperskill/HyperskillAnalyticTarget.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/domain/analytic/PaywallClickedTermsOfServiceAndPrivacyPolicyHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/injection/PaywallComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/injection/PaywallFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallReducer.kt, shared/src/commonMain/resources/MR/base/strings.xml
[#ALTAPPS-1154](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1154)
**Checklist**
- Adds terms button to paywall
=> ALTAPPS-1154: Shared, iOS add terms link to Paywall

shared/src/commonMain/kotlin/org/hyperskill/app/onboarding/cache/OnboardingCacheDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/onboarding/cache/OnboardingCacheKeyValues.kt, shared/src/commonMain/kotlin/org/hyperskill/app/onboarding/data/repository/OnboardingRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/onboarding/data/source/OnboardingCacheDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/onboarding/domain/interactor/OnboardingInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/onboarding/domain/repository/OnboardingRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/presentation/WelcomeOnboardingActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/presentation/WelcomeOnboardingFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/presentation/WelcomeOnboardingReducer.kt
[#ALTAPPS-1091](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1091)
**Checklist**
- Removes notification onboarding shown flag usages
=> ALTAPPS-1091: Shared remove check for wasNotificationOnboardingShown flag

shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeatureKeys.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeaturesMap.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/injection/StepComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/injection/StepDataComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/injection/StepFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/presentation/StepActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/presentation/StepFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/presentation/StepReducer.kt
[#ALTAPPS-1156](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1156)
**Checklist**
- Adds experiment with short theory
=> ALTAPPS-1156: Shared experiment with short theory

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/ViewControllers/AppRouter.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/ViewControllers/AppViewController.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProfileSettings/ProfileSettingsViewModel.swift
- Fixes code duplication via `AppRouter`
=> iOS: Add AppRouter

shared/src/commonMain/kotlin/org/hyperskill/app/home/injection/HomeComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/injection/HomeFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeReducer.kt
[#ALTAPPS-767](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-767)
**Checklist**
- Fixes Home screen not updates problem of the day after topic is completed
=> ALTAPPS-767: Shared fix Home screen not updates problem of the day after topic is completed

androidHyperskillApp/src/main/java/org/hyperskill/app/android/problems_limit/view/ui/delegate/ProblemsLimitDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/fragment/StudyPlanFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/users_questionnaire/delegate/UsersQuestionnaireCardDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/users_questionnaire/ui/UsersQuestionnaireWidget.kt, androidHyperskillApp/src/main/res/drawable/ic_user_questionnaire_close.xml, androidHyperskillApp/src/main/res/layout/fragment_study_plan.xml, shared/src/androidMain/kotlin/org/hyperskill/app/study_plan/presentation/StudyPlanScreenViewModel.kt
[ALTAPPS-1144](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1144)
**Checklist**
- Implements user questionnaire widget
=> ALTAPPS-1144: Android widget for users questionnaire

gradle/app.versions.toml, iosHyperskillApp/NotificationServiceExtension/Info.plist, iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Info.plist, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/ProfileView.swift, iosHyperskillApp/iosHyperskillAppTests/Info.plist, iosHyperskillApp/iosHyperskillAppUITests/Info.plist
- Fixes a fatal error on iOS -> No ObservableObject of type PanModalPresenter found in `ProfileDailyStudyRemindersHourIntervalPickerView`
=> Hotfix 1.50.1

iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/Views/PaywallView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProfileSettings/ProfileSettingsViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProfileSettings/Views/ProfileSettingsSubscriptionSectionView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProfileSettings/Views/ProfileSettingsView.swift
[#ALTAPPS-1138](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1138)
**Checklist**
- Adds subscription info in profile
=> ALTAPPS-1138: iOS subscription info in profile

shared/src/commonMain/kotlin/org/hyperskill/app/paywall/domain/analytic/PaywallSubscriptionPurchasedAppsFlyerAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallReducer.kt, shared/src/commonTest/kotlin/org/hyperskill/paywall/PaywallTest.kt
[#ALTAPPS-1164](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1164)
**Checklist**
- Adds `af_subscribe` event
=> ALTAPPS-1164: Shared add subscription subscribe AppsFlyer analytic event

iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/StepViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepView.swift
[#ALTAPPS-1187](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1187)
**Checklist**
- Adds support for `StepFeature.ScreenHidden`
=> ALTAPPS-1187: iOS support StepFeature.ScreenHidden for time spent events

androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthSocialFragment.kt
[ALTAPPS-917](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-917)
**Checklist**
- Don't log cancellation exception of Google auth
=> ALTAPPS-917: Android Filter out redundant google auth exceptions

androidHyperskillApp/src/internalRelease/java/org/hyperskill/app/android/debug/DebugScreen.kt
[ALTAPPS-1151](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1151)
**Checklist**
- Add missed argument for `DebugFragement` in the `internalRelease` flavor
=> ALTAPPS-1151: Fix android internalRelease build

.github/actions/setup-android/action.yml, .github/actions/setup-ios/action.yml
[#ALTAPPS-1192](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1192)
**Checklist**
- Bumps Java from 17 to 19
=> ALTAPPS-1192: CI/CD bump Java from 17 to 19

shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/injection/StudyPlanWidgetComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetReducer.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/widget/StudyPlanWidgetTest.kt
[#ALTAPPS-1186](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1186)
**Checklist**
- Hides next project section for freemium users
=> ALTAPPS-1186: Shared filter next project section for freemium users in study plan

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_code/view/delegate/CodeStepQuizFormDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_code/view/fragment/CodeStepQuizFragment.kt, androidHyperskillApp/src/main/res/drawable/code_badge_fix_mistakes_background.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_code.xml
[ALTAPPS-1175](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1175)
**Checklist**
- add fix-mistakes badge on code stepQuiz screen
=> ALTAPPS-1175: Android add fix-mistakes badge on code stepQuiz screen

.github/workflows/ci.yml, config/detekt/baseline.xml, config/detekt/detekt.yml, shared/src/androidMain/kotlin/org/hyperskill/app/network/PreconfiguredHttpClient.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizResolver.kt, shared/src/commonMain/kotlin/org/hyperskill/app/submissions/cache/SubmissionsCacheDataSourceImpl.kt
[#ALTAPPS-1180](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1180)
**Checklist**
1. Integrates `detekt` into CI workflow
2. Suppresses issues in source files
=> ALTAPPS-1180: GitHub Actions integrate detekt into CI workflow

.github/actions/setup-ios/action.yml
[#ALTAPPS-1206](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1206)
**Checklist**
- Bumps Xcode version from 15.2 to 15.3
=> ALTAPPS-1206: GitHub Actions bump Xcode version from 15.2 to 15.3

androidHyperskillApp/src/main/java/org/hyperskill/app/android/paywall/ui/PaywallContent.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/paywall/ui/PaywallPreviewDefaults.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/paywall/ui/PaywallScreen.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/paywall/ui/SubscriptionDetails.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/injection/PaywallComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/injection/PaywallFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/view/PaywallViewStateMapper.kt, shared/src/commonMain/resources/MR/base/strings.xml
[ALTAPPS-1214](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1214)
**Checklist**
- Add explicit subscription price and period
=> ALTAPPS-1214: Android add explicit subscription price and duration on paywall screen

androidHyperskillApp/src/main/java/org/hyperskill/app/android/request_review/dialog/RequestReviewDialogFragment.kt
[ALTAPPS-1211](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1211)
**Checklist**
- Dismiss `RequestReviewDialogFragment` in `onAction` only if it is in the Resumed state;
- Dismiss `RequestReviewDialogFragment` in `onStart` lifecycle callback if it wasn't dismissed in `onAction`.
=> ALTAPPS-1211: Android fix crash on request review modal

iosHyperskillApp/iosHyperskillApp/Sources/Extensions/UIKit/UINavigationControllerExtensions.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Routers/TabBarRouter.swift
[#ALTAPPS-1219](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1219)
**Checklist**
- Possible fix of tab bar disappears on training screen after limits reached modal navigation
=> ALTAPPS-1219: iOS fix tab bar disappears on training screen after limits reached modal navigation

androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthCredentialsFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/challenge/delegate/ChallengeCardDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/extensions/ContextExtensions.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/extensions/CustomTabsExtention.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/extensions/LoggerUtils.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/view/ui/widget/ExternalLinkWebViewClient.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/view/ui/widget/ProgressableWebViewClient.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/manage_subscription/fragment/ManageSubscriptionFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/paywall/fragment/PaywallFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/delegate/AboutMeDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/delegate/ProfileViewActionDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile_settings/view/dialog/ProfileSettingsDialogFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/request_review/dialog/RequestReviewDialogFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/fragment/StudyPlanFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/users_questionnaire/delegate/UsersQuestionnaireCardDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/view/base/ui/extension/SocialNetworksRedirectExtensions.kt, shared/src/commonMain/resources/MR/base/strings.xml
[ALTAPPS-1212](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1212)
**Checklist**
- Wrap `CustomTabsIntent.lauchUrl()` call with try/catch, to catch `ActivityNotFoundException`;
- Add logging of these exceptions;
- Add logging of the same exception for plain URL launch in the browser.
=> ALTAPPS-1212: Android fix custom tabs call crash

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Extensions/SwiftUI/View/View+ConditionalOpacity.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizChoice/Views/StepQuizChoiceView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCode/Views/StepQuizCodeEditorView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCode/Views/StepQuizCodeView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizFillBlanks/Views/StepQuizFillBlanksView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizMatching/Views/StepQuizMatchingView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizParsons/Views/StepQuizParsonsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizPyCharm/StepQuizPyCharmView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizSQL/Views/StepQuizSQLView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizSorting/Views/StepQuizSortingView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizString/Views/StepQuizStringView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizTable/Views/StepQuizTableView.swift
[#ALTAPPS-1224](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1224)
**Checklist**
- Adds disabled state handling for remaining quizzes
=> ALTAPPS-1224: iOS adjust colors for disabled quiz state

shared/src/commonMain/kotlin/org/hyperskill/app/network/NetworkBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/submissions/remote/SubmissionsRemoteDataSourceImpl.kt
[ALTAPPS-1229](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1229)
**Checklist**
- Add socketTimeout for `POST /api/submissions` request
- Add error logging for submission creation
=> ALTAPPS-1229: Shared increase socketTimeout for POST /api/submissions

gradle/app.versions.toml, iosHyperskillApp/NotificationServiceExtension/Info.plist, iosHyperskillApp/Podfile, iosHyperskillApp/Podfile.lock, iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Info.plist, iosHyperskillApp/iosHyperskillAppTests/Info.plist, iosHyperskillApp/iosHyperskillAppUITests/Info.plist
- Bumps AppsFlyerFramework on iOS #1008
=> Hotfix 1.55.1

androidHyperskillApp/src/main/java/org/hyperskill/app/android/paywall/ui/PaywallContent.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/paywall/ui/PaywallPreviewDefaults.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/paywall/ui/PaywallScreen.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/paywall/ui/SubscriptionDetails.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/injection/PaywallComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/injection/PaywallFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/view/PaywallViewStateMapper.kt, shared/src/commonMain/resources/MR/base/strings.xml
[#ALTAPPS-1230](https://vyahhi.myjetbrains.com/issue/ALTAPPS-1230)
**Checklist**
- This reverts commit https://github.com/hyperskill/mobile-app/commit/12390e932fe37beb5cde39d9926e20d294c4aade
- Now the subscription price is placed in the CTA as it used to be.
=> ALTAPPS-1230: Android revert paywall subscription price and duration text update

shared/src/androidUnitTest/kotlin/org/hyperskill/step_quiz/AndroidStepQuizTest.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/injection/StepQuizFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_toolbar/presentation/StepQuizToolbarFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_toolbar/presentation/StepQuizToolbarReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_toolbar/presentation/StepQuizToolbarResolver.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_toolbar/view/StepQuizToolbarViewStateMapper.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz/StepQuizTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_toolbar/StepQuizToolbarTest.kt
[#ALTAPPS-1225](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1225)
**Checklist**
- Makes changes according to this [comment](https://vyahhi.myjetbrains.com/youtrack/issue/ALTUX-2815/Feature-Improve-limits-flow-in-mobile-apps#focus=Comments-74-291603.0-0)
=> ALTAPPS-1225: Shared show limits in toolbar only for supported StepRoute types

shared/src/commonMain/kotlin/org/hyperskill/app/problems_limit_info/injection/ProblemsLimitInfoModalFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/problems_limit_info/view/ProblemsLimitInfoModalViewStateMapper.kt
[#ALTAPPS-1240](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1240)
**Checklist**
- Checks that `stepsLimitResetTime` is not in the past before formatting reset in text
=> ALTAPPS-1240: Shared incorrect limits reset time formatted string in problems limit info bottom sheet

shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/interactor/AnalyticInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/AnalyticEventUserProperties.kt, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/hyperskill/HyperskillAnalyticKeys.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeaturesMap.kt
[#ALTAPPS-1233](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1233)
**Checklist**
- Adds features map to user properties
=> ALTAPPS-1233: Shared add features map to user properties

iosHyperskillApp/TestPlans/AllTests.xctestplan, iosHyperskillApp/TestPlans/UnitTests.xctestplan, iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp.xcodeproj/xcshareddata/xcbaselines/2C919DEC27EEF5BC0022A2F2.xcbaseline/ADDDB70F-EE79-4C0E-9923-72C0A4A25AEF.plist, iosHyperskillApp/iosHyperskillApp.xcodeproj/xcshareddata/xcbaselines/2C919DEC27EEF5BC0022A2F2.xcbaseline/Info.plist, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/Model/Analyze/CodePlaygroundManager.swift, iosHyperskillApp/iosHyperskillAppTests/FrameworksTests/CodeEditor/CodePlaygroundManager/CodePlaygroundGetChangesSubstringPerformanceTests.swift, iosHyperskillApp/iosHyperskillAppTests/FrameworksTests/CodeEditor/CodePlaygroundManager/CodePlaygroundGetChangesSubstringTests.swift, iosHyperskillApp/iosHyperskillAppTests/FrameworksTests/CodeEditor/CodePlaygroundManager/CodePlaygroundGetCurrentTokenTests.swift, iosHyperskillApp/iosHyperskillAppTests/FrameworksTests/CodeEditor/CodePlaygroundManager/CodePlaygroundShouldMakeTabLineAfterTests.swift
**Checklist**
-  Optimizes `getChangesSubstring`
- This optimized version uses `zip` and `enumerated` to find the first non-matching character, reducing the complexity by directly working with the differences between the two strings.
=> ALTAPPS-637: iOS CodePlaygroundManager optimize getChangesSubstring

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp.xcodeproj/xcshareddata/xcbaselines/2C919DEC27EEF5BC0022A2F2.xcbaseline/ADDDB70F-EE79-4C0E-9923-72C0A4A25AEF.plist, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/Model/Analyze/CodePlaygroundManager.swift, iosHyperskillApp/iosHyperskillAppTests/FrameworksTests/CodeEditor/CodePlaygroundManager/CodePlaygroundGetCurrentTokenPerformanceTests.swift, iosHyperskillApp/iosHyperskillAppTests/FrameworksTests/CodeEditor/CodePlaygroundManager/CodePlaygroundGetCurrentTokenTests.swift, iosHyperskillApp/iosHyperskillAppTests/FrameworksTests/CodeEditor/CodePlaygroundManager/CodePlaygroundShouldMakeTabLineAfterTests.swift
**Checklist**
- Optimizes `getCurrentToken(text:cursorPosition:)`
- Reduces the number of index checks and potentially expensive subscript operations that are repeated multiple times during execution. Utilize Swift's more efficient String processing features.
=> ALTAPPS-637: iOS CodePlaygroundManager optimize getCurrentToken(text:cursorPosition:)

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/delegate/StepRouterDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/fragment/StepFragment.kt
[ALTAPPS-1228](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1228)
**Checklist**
- Fix app crash during back navigation via system back gesture or button
=> ALTAPPS-1228: Fix app crash when navigate back from in step screen

iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/View/SwiftUI/CodeEditor.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/View/SwiftUI/CodeEditorSuggestionsPresentationContextProviding.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/View/UIKit/CodeEditorView/CodeEditorView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCode/Views/StepQuizCodeEditorView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCodeFullScreen/Views/StepQuizCodeFullScreenCodeView.swift
**Checklist**
1. Enables code completion
2. Fixes an issue with providing presentation controller for completions
=> ALTAPPS-637: iOS CodeEditor enable code completion

.github/actions/setup-ios/action.yml
[#ALTAPPS-1261](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1261)
**Checklist**
- Bumps Xcode version from 15.3 to 15.4
=> ALTAPPS-1261: GitHub Actions bump Xcode version from 15.3 to 15.4

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/StepQuizViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizFillBlanks/InputOutput/StepQuizFillBlanksOutputProtocol.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizFillBlanks/StepQuizFillBlanksViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizFillBlanks/ViewData/StepQuizFillBlanksViewDataMapper.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizFillBlanks/ViewData/StepQuizFillBlanksViewDataMapperCache.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizFillBlanks/Views/StepQuizFillBlanksView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizFillBlanks/Views/UIKit/FillBlanksQuizView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizFillBlanksSelectOptions/Views/StepQuizFillBlanksSelectOptionsViewWrapper.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizFillBlanksSelectOptions/Views/UIKit/Cell/StepQuizFillBlanksSelectOptionsCollectionViewCell.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizFillBlanksSelectOptions/Views/UIKit/Cell/StepQuizFillBlanksSelectOptionsCollectionViewCellContainerView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizFillBlanksSelectOptions/Views/UIKit/StepQuizFillBlanksSelectOptionsView.swift
[#ALTAPPS-1256](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1256)
**Checklist**
- Fill in the blanks with selects UI improvements
=> ALTAPPS-1256: iOS fill in the blanks with selects UI improvements

iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/ToolbarProgress/SpacebotRocketAnimationView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/ToolbarProgress/SpacebotWowAnimationView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/ToolbarProgress/StepToolbarProgressView.swift
[#ALTAPPS-1255](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1255)
**Checklist**
- Fixes animation when application enters foreground after being inactive
=> ALTAPPS-1255: iOS fix spacebot animation stucks if user minimizes the app

iosHyperskillApp/iosHyperskillApp/Sources/Extensions/Shared/Model/StepExtensions.swift, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeatureKeys.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/domain/model/Step.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/interactor/StepQuizInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizResolver.kt, shared/src/commonTest/kotlin/org/hyperskill/ReplySerializationTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step/domain/model/StepStub.kt
[#ALTAPPS-1263](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1263)
**Checklist**
Change feature flag name and disable easy steps for code generation with errors
=> ALTAPPS-1263: Shared code generation with errors improvements

androidHyperskillApp/src/main/res/layout/fragment_auth_email.xml, androidHyperskillApp/src/main/res/layout/fragment_auth_social.xml
[ALTAPPS-914](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-914)
**Checklist**
- Make auth error text selectable to allow copy it.
=> Make auth error text copyable

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_code/view/fragment/CodeStepQuizFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_stage_step_wrapper.xml, androidHyperskillApp/src/main/res/layout/fragment_step_practice.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_code_keyboard_extension.xml
[ALTAPPS-1257](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1257)
**Checklist**
- Add keyboard extension recycler statically to the `StepPracticeFragement` &  `StageStepWrapper`, to not be affected by the root view group.
=> ALTAPPS-1257: Android fix app crash when open code quiz

iosHyperskillApp/fastlane/metadata/en-US/name.txt, iosHyperskillApp/fastlane/metadata/en-US/subtitle.txt
[#ALTAPPS-](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-)
**Checklist**
* Updated name and subtitle for better ASO
=> [ASO] Name and subtitle

shared/src/commonMain/resources/MR/base/strings.xml
[ALTUX-2678](https://vyahhi.myjetbrains.com/youtrack/issue/ALTUX-2678)
**Checklist**
Rename tracks to courses
=> ALTUX-2678: Rename tracks to courses

iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Systems/AmplitudeManager.swift, shared/src/androidMain/kotlin/org/hyperskill/app/analytic/domain/amplitude/AndroidAmplitudeAnalyticEngine.kt, shared/src/androidMain/kotlin/org/hyperskill/app/core/injection/CommonAndroidAppGraphImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/interactor/AnalyticInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/Analytic.kt, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/AnalyticEventUserProperties.kt, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/AnalyticKeys.kt, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/hyperskill/HyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/processor/AmplitudeAnalyticEventMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/processor/AnalyticHyperskillEventProcessor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/purchases/domain/interactor/PurchaseInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/purchases/injection/PurchaseComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/sentry/domain/model/breadcrumb/HyperskillSentryBreadcrumbAnalyticEventMapper.kt, shared/src/commonTest/kotlin/org/hyperskill/AnalyticHyperskillRequestTest.kt, shared/src/commonTest/kotlin/org/hyperskill/analytic/domain/processor/AmplitudeAnalyticEventMapperTest.kt, shared/src/iosMain/kotlin/org/hyperskill/app/core/injection/IosAppComponentImpl.kt
**Checklist**
- Store user properties as a map in `AnalyticInteractor`;
- Add `can_make_payments` user property to analytics;
- Log errors during purchase & price loading in the `PaywallActionDispatcher`
=> Shared add purchase error logging & analytic

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/StepViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepTheoryContentView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepToolbarContent.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepFeedback/StepFeedbackAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepFeedback/StepFeedbackViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizToolbarContent.swift
[#ALTAPPS-1268](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1268)
**Checklist**
Adds step quiz controls on iOS
=> ALTAPPS-1268: iOS step quiz controls

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/delegate/StepDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt, config/detekt/baseline.xml, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/step_completion/presentation/StepCompletionFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_completion/presentation/StepCompletionReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizReducer.kt, shared/src/commonTest/kotlin/org/hyperskill/step_completion/StepCompletionTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz/StepQuizTest.kt
[#ALTAPPS-1269](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1269)
**Checklist**
Improves solving step behavior:
1. Haptic feedback view actions
2. Scroll to call to action button view action
=> ALTAPPS-1269: iOS, shared improve solving step behavior

androidHyperskillApp/src/main/AndroidManifest.xml, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/extensions/HapticFeedbackExtentions.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/extensions/NestedScollViewExtention.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/stage_implementation/delegate/StageStepMenuDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/stage_implementation/fragment/StageStepWrapperFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/delegate/StepDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/delegate/StepMenuDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/fragment/StepFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_practice/model/StepPracticeHost.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_practice/view/fragment/StepPracticeFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/model/StepQuizButtonsState.kt, gradle/libs.versions.toml
[ALTAPPS-1270](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1270)
**Checklist**
- Implement scroll down to the step quiz screen;
- Use HapticFeddback API for step quiz haptic feedback.
=> ALTAPPS-1270: Android improve step solving behaviour

iosHyperskillApp/Podfile, iosHyperskillApp/Podfile.lock, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StageImplement/StageImplementView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Systems/AppAppearance.swift, iosHyperskillApp/iosHyperskillApp/Sources/Systems/KeyboardManager.swift
[#ALTAPPS-1241](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1241)
**Checklist**
- Fixes navigation bar is transparent when keyboard is active
=> ALTAPPS-1241: iOS fix navigation bar is transparent when keyboard is active

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/view/ui/widget/compose/HyperskillCard.kt
[ALTAPPS-1287](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1287)
**Checklist**
- Fix padding modifier usage
=> ALTAPPS-1287: Android fix challenge card padding

androidHyperskillApp/src/main/java/org/hyperskill/app/android/main/view/ui/activity/MainActivity.kt
[ALTAPPS-468](https://vyahhi.myjetbrains.com/issue/ALTAPPS-468)
**Checklist**
- Add margin for the whole content if the navigation bar is shown on the left or right side.
=> ALTAPPS-468: Fix insets handling

shared/src/commonMain/kotlin/org/hyperskill/app/step/injection/StepFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/presentation/StepActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/presentation/ViewStepActionDispatcher.kt
[#ALTAPPS-1297](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1297)
**Checklist**
- Adds `ViewStepActionDispatcher` that handles `StepFeature.InternalAction.ViewStep`
=> ALTAPPS-1297: Shared send step viewed request after feature destroying

androidHyperskillApp/proguard-rules.pro, gradle.properties, gradle/app.versions.toml
[ALTAPPS-1304](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1304)
**Checklist**
- Revert R8 fullmode
=> ALTAPPS-1304: Revert R8 fullMode

androidHyperskillApp/src/main/java/org/hyperskill/app/android/stage_implementation/fragment/StageStepWrapperFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/delegate/StepDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/fragment/StepWrapperFragment.kt, iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/PaywallViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/Views/Content/PaywallContentView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/Views/Content/PaywallFooterView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/Views/PaywallView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/StepViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/Model/StudyPlanWidgetViewStateSectionItemStateWrapper.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/StudyPlanAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/StudyPlanViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/Views/Section/List/Item/StudyPlanSectionItemIconView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/Views/Section/StudyPlanSectionView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/Views/StudyPlanPaywallBanner.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/Views/StudyPlanView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicCompletedModal/TopicCompletedModalOutputProtocol.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicCompletedModal/TopicCompletedModalViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicCompletedModal/Views/TopicCompletedModalView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/step_completion/presentation/StepCompletionFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_completion/presentation/StepCompletionReducer.kt
[#ALTAPPS-1309](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1309)
**Checklist**
- Adds support for content trial monetization model on iOS
=> ALTAPPS-1309: iOS mobile content trial

iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProjectSelection/List/Views/Grid/Cell/ProjectSelectionListGridCellBadgesView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCodeBlanks/Views/StepQuizCodeBlanksSuggestionsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/Views/Section/List/Item/StudyPlanSectionItemBadgesView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TrackSelection/List/Views/Grid/Cell/TrackSelectionListGridCellBadgesView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Views/SwiftUI/Layouts/FlowLayout.swift
[#ALTAPPS-769](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-769)
**Checklist**
1. Adds `FlowLayoutCompatibility`
2. Uses `FlowLayoutCompatibility` when rendering badges
=> ALTAPPS-769: iOS badges wrapping view

iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/StudyPlanViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/Views/Section/StudyPlanSectionView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/Views/StudyPlanView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/analytic/StudyPlanAnalyticKeys.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/analytic/StudyPlanAnalyticParams.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/analytic/StudyPlanClickedRetryActivitiesLoadingHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/analytic/StudyPlanClickedSectionHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/analytic/StudyPlanLoadMoreActivitiesClickedHSAnalyticEvent.kt
[#ALTAPPS-1302](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1302)
**Checklist**
- Add `Load more` button
=> ALTAPPS-1302: iOS root topics section pagination

shared/src/commonMain/kotlin/org/hyperskill/app/subscriptions/domain/model/SubscriptionType.kt
**Checklist**
- Set `isProjectionSelectionAvailable` frag to true for TEAM_MEMBER Subscription.
=> Shared: Fix project selection for TEAM_MEMBER users

iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizTableSelectColumns/StepQuizTableSelectColumnsColumnView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizTableSelectColumns/StepQuizTableSelectColumnsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizTableSelectColumns/StepQuizTableSelectColumnsViewController.swift
[#ALTAPPS-1288](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1288)
**Checklist**
- Automatically confirm selection for single choices
=> ALTAPPS-1288: iOS improve table problem with one option flow

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_table/view/fragment/TableColumnSelectionBottomSheetDialogFragment.kt
[ALTAPPS-1289](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1289)
**Checklist**
- Dismiss the `TableColumnSelectionBottomSheetDialogFragment` by clicking on the option for `SingleChoiceSelectionHelper`.
=> ALTAPPS-1289: Android improve table problem with one option flow

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_table/view/fragment/TableColumnSelectionBottomSheetDialogFragment.kt
[ALTAPPS-1289](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1289)
**Checklist**
Hide confirm button if only one option can be selected
=> ALTAPPS-1289: Hide singleChoice table problem confirm button

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/delegate/StepMenuDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/fragment/StepWrapperFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/model/StepMenuPrimaryAction.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/presentation/StepFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/view/mapper/StepViewStateMapper.kt, shared/src/commonTest/kotlin/org/hyperskill/step/StepViewStateMapperTest.kt
[ALTAPPS-1313](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1313)
**Checklist**
- Add `StepFeature.ViewState.isCommentsToolbarItemAvailable`;
- Add condition for theory step condition for  `StepMenuSecondaryAction.COMMENTS`;
- Update render logic on the Android platform;
- Update existing tests and create new.
=> ALTAPPS-1313: Shared, Android make primary comments action available for theory step

shared/src/commonMain/moko-resources/base/strings.xml
=> Rename skip to postpone to sustain consistency with web

iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/Model/CodeLanguage.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/Model/CodeLanguageSamples/CodeLanguageSamples.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizFillBlanks/ViewData/StepQuizFillBlanksViewDataMapper.swift
[#ALTAPPS-1189](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1189)
**Checklist**
- Adds support for MySQL and fallbacks to auto highlighting if language is not supported
=> ALTAPPS-1189: iOS fix "undefined" values in fill blanks problem because the highlight language is not supported

iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/PanModal/PanModalPresenter.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StageImplement/StageImplementAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StageImplement/StageImplementView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StageImplement/StageImplementViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/StepViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/StepQuizViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift
[#ALTAPPS-1321](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1321)
**Checklist**
- Fixes an issue with data loading for steps
=> ALTAPPS-1321: iOS fix attempt is outdated when creating submission

.github/actions/setup-android/action.yml, .github/actions/setup-ios/action.yml, .github/workflows/android_beta_deployment.yml, .github/workflows/android_deploy_to_firebase.yml, .github/workflows/android_deploy_to_firebase_manually.yml, .github/workflows/android_release_deployment.yml, .github/workflows/automerge_into_release.yml, .github/workflows/build_caches.yml, .github/workflows/ci.yml, .github/workflows/cleanup_pr_caches.yml, .github/workflows/codeql.yml, .github/workflows/detect_changed_files_reusable_workflow.yml, .github/workflows/gh_pages_analytics.yml, .github/workflows/ios_beta_deployment.yml, .github/workflows/ios_release_deployment.yml, .github/workflows/ios_unit_testing.yml, .github/workflows/merge_main_into_develop.yml
Bumps:
1. [ruby/setup-ruby](https://github.com/hyperskill/mobile-app/commit/10d8c95040f4972a2e84ee031a62f06ef612c6ee)
2. [actions/setup-java](https://github.com/hyperskill/mobile-app/commit/746814598b2153e0e7f50d31664bf08f777d3649)
3. [actions/checkout](https://github.com/hyperskill/mobile-app/commit/be61d345e3b8dfcbb2956df2f8ea031fd2da373e)
=> GitHub Actions: Bump actions

androidHyperskillApp/src/main/java/org/hyperskill/app/android/stage_implementation/fragment/StageImplementationFragment.kt
[ALTAPPS-1320](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1320)
**Checklist**
- Fix `StageImplementationFragment` does not implement `StepNavigationContainer` interface which is required to successfully call `requireStepRouter` in `StepDelegate`.
=> [Android] Fix StageImplementationFragment crash

androidHyperskillApp/fastlane/metadata/android/en-US/title.txt, androidHyperskillApp/src/main/AndroidManifest.xml, androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthCredentialsFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/auth/view/ui/fragment/AuthSocialFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_welcome.xml, iosHyperskillApp/fastlane/metadata/en-US/name.txt, iosHyperskillApp/fastlane/metadata/en-US/promotional_text.txt, iosHyperskillApp/iosHyperskillApp/Info.plist, iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift, shared/src/androidMain/kotlin/org/hyperskill/app/core/domain/platform/Platform.kt, shared/src/commonMain/kotlin/org/hyperskill/app/core/domain/platform/Platform.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/domain/model/FeedbackEmailDataBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/presentation/ProfileSettingsActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/request_review/modal/injection/RequestReviewModalComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/request_review/modal/injection/RequestReviewModalFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/request_review/modal/view/mapper/RequestReviewModalViewStateMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/questionnaire/view/WelcomeQuestionnaireViewStateMapper.kt, shared/src/commonMain/moko-resources/base/strings.xml, shared/src/iosMain/kotlin/org/hyperskill/app/application_shortcuts/domain/interactor/ApplicationShortcutsInteractor.kt, shared/src/iosMain/kotlin/org/hyperskill/app/core/domain/platform/Platform.kt
[#ALTAPPS-1325](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1325)
**Checklist**
- Removes "My" prefix from the iOS app name
=> ALTAPPS-1325: iOS remove "My" prefix from the app name in App Store

iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/Header/StepQuizNameView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizMatching/StepQuizMatchingView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizSorting/Views/StepQuizSortingIcon.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizSorting/Views/StepQuizSortingItemView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizTable/Views/StepQuizTableRowView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizTable/Views/StepQuizTableView.swift
[#ALTAPPS-1331](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1331)
**Checklist**
- Improves problems UI
=> ALTAPPS-1331: iOS improve problems UI

androidHyperskillApp/src/main/java/org/hyperskill/app/android/paywall/ui/PaywallScreen.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/Views/Content/PaywallContentView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/Views/Content/PaywallFooterView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/Views/PaywallView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Systems/PurchaseManager.swift, shared/src/androidMain/kotlin/org/hyperskill/app/purchases/domain/AndroidPurchaseManager.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/view/PaywallViewStateMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/purchases/domain/interactor/PurchaseInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/purchases/domain/model/PurchaseManager.kt, shared/src/commonMain/moko-resources/base/strings.xml, shared/src/commonTest/kotlin/org/hyperskill/paywall/PaywallTest.kt, shared/src/iosMain/kotlin/org/hyperskill/app/purchases/domain/manager/IosPurchaseManager.kt, shared/src/iosMain/kotlin/org/hyperskill/app/purchases/domain/manager/IosPurchaseManagerImpl.kt
[#ALTAPPS-1332](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1332)
**Checklist**
1. Check trial eligibility for subscription
2. Render trial text
=> ALTAPPS-1332: iOS support 1 week free trial state on paywall screen

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt, config/detekt/baseline.xml, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizActionButtons/StepQuizActionButton.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizActionButtons/StepQuizActionButtons.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCodeBlanks/Views/StepQuizCodeBlanksSuggestionsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCodeBlanks/Views/StepQuizCodeBlanksView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizChildFeatureReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/view/mapper/StepQuizCodeBlanksViewStateMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/view/model/StepQuizCodeBlanksViewState.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/StepQuizCodeBlanksReducerTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/StepQuizCodeBlanksViewStateMapperTest.kt
[#ALTAPPS-1329](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1329)
**Checklist**
- Add code blanks onboarding for 47329 step
=> ALTAPPS-1329: iOS add code blanks onboarding for 47329 step

shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/root/presentation/WelcomeOnboardingReducer.kt
[#ALTAPPS-1338](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1338)
**Checklist**
- Reverts direct redirect to Python track
=> ALTAPPS-1338: Shared rollback auto choosing Python track

config/detekt/baseline.xml, iosHyperskillApp/iosHyperskillApp/Sources/Extensions/Shared/Model/BlockOptionsExtensions.swift, shared/src/commonMain/kotlin/org/hyperskill/app/step/domain/model/Block.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/domain/model/CodeBlock.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/domain/model/template/CodeBlanksTemplateMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/domain/model/template/CodeBlockTemplateEntry.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/domain/model/template/CodeBlockTemplateEntryType.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksResolver.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksStateExtensions.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/view/mapper/StepQuizCodeBlanksViewStateMapper.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducerDeleteButtonClickedTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducerElifAndElseStatementsSuggestionsAvailabilityTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/template/CodeBlanksTemplateMapperTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/view/StepQuizCodeBlanksViewStateMapperIsDeleteButtonEnabledTest.kt
[#ALTAPPS-1353](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1353)
**Checklist**
1. Adds `Step.Block.Options.codeBlanksTemplate`
2. Adds `CodeBlanksTemplateMapper` to initialize code blocks feature with provided template elements
=> ALTAPPS-1353: Shared code blanks template JSON format

shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeatureKeys.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeaturesMap.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/root/presentation/WelcomeOnboardingReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/track_details/injection/WelcomeOnboardingTrackDetailsComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/track_details/injection/WelcomeOnboardingTrackDetailsFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/track_details/presentation/WelcomeOnboardingTrackDetailsFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/track_details/presentation/WelcomeOnboardingTrackDetailsReducer.kt
[#ALTAPPS-1356](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1356)
**Checklist**
- Adds Python adopted course selection
=> ALTAPPS-1356: Shared Python adopted course selection

config/detekt/baseline.xml, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCodeBlanks/Views/CodeBlocks/ActionButtons/StepQuizCodeBlanksActionButton.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCodeBlanks/Views/CodeBlocks/ActionButtons/StepQuizCodeBlanksActionButtonsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCodeBlanks/Views/CodeBlocks/StepQuizCodeBlanksCodeBlocksView.swift, shared/src/androidUnitTest/kotlin/org/hyperskill/step_quiz/AndroidStepQuizTest.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/injection/StepQuizCodeBlanksComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksOnboardingReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksResolver.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/view/model/StepQuizCodeBlanksViewState.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz/presentation/StepQuizChildFeatureReducerStub.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducerCodeBlockChildClickedTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducerCodeBlockClickedTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducerDecreaseIndentLevelButtonClickedTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducerDeleteButtonClickedTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducerEnterButtonClickedTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducerInitializeTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducerOnboardingTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducerSpaceButtonClickedTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducerStub.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducerSuggestionClickedTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/view/StepQuizCodeBlanksViewStateTest.kt
[#ALTAPPS-1357](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1357)
**Checklist**
- Adds onboarding for more steps
=> ALTAPPS-1357: Shared, iOS code blanks mechanics onboarding

shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/domain/model/template/CodeBlanksTemplateMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksResolver.kt
[#ALTAPPS-1346](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1346)
**Checklist**
- Fixes resolving code blanks elif else blocks suggestions
=> ALTAPPS-1346: Shared fix code blanks elif else blocks suggestions
