hyperskill/mobile-app

iosHyperskillApp/Podfile, iosHyperskillApp/Podfile.lock, iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/AppDelegate.swift, iosHyperskillApp/iosHyperskillApp/Sources/Extensions/ThirdParty/Nuke/ImageDecoders+SVG.swift, iosHyperskillApp/iosHyperskillApp/Sources/Systems/NukeManager.swift
**Reviewers**
- Adds support for lazy image loading via [NukeUI](https://github.com/kean/NukeUI)
- Supports SVG image rendering via [SVGKit](https://github.com/SVGKit/SVGKit)
Example usage:
```swift
LazyImage(source: "https://hyperskill.org/media/tracks/0580353297be4214ab9ed7be8ce75d3d/Kotlin.svg")
.frame(width: 64, height: 64)
.addBorder(color: Color(ColorPalette.onSurfaceAlpha12), cornerRadius: 128)
```
=> iOS LazyImage + SVG

iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizTableSelectColumns/StepQuizTableSelectColumnsViewController.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizTableSelectColumns/Views/StepQuizTableSelectColumnsColumnView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizTableSelectColumns/Views/StepQuizTableSelectColumnsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Views/CheckboxButton.swift
Task: [#ALTAPPS-260](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-260)
- !
**Reviewers**
- Adds `Confirm` button for table single choice
- Fixes indicators colors in dark mode
=> ALTAPPS-260: iOS add Confirm button for table single choice

iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/HomeViewModel.swift
Task: [#ALTAPPS-255](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-255)
- !
**Reviewers**
- Add observing active and background notifications in HomeViewModel
=> ALTAPPS-255: iOS reload home screen after entering app from background

shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/injection/ProfileSettingsComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/injection/ProfileSettingsFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/presentation/ProfileSettingsActionDispatcher.kt
Task: [#ALTAPPS-294](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-294)
- !
**Reviewers**
- Add clearing auth cache before emiting UserDeauthorized
=> ALTAPPS-294: iOS logout infinite loading fix

iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/TopicsRepetitionsViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/TopicsRepetitionsView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/topics_repetitions/presentation/TopicsRepetitionsFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics_repetitions/presentation/TopicsRepetitionsReducer.kt
Task: [#ALTAPPS-433](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-433Android-Topics-repetitions-views)
**Reviewers**
- Move clicks handling and analytics sanding into shared module to use it on Android side
=> ALTAPPS-433: move topics-repetition screen click handling into shared

androidHyperskillApp/src/main/assets/css/step.css, androidHyperskillApp/src/main/java/org/hyperskill/app/android/latex/view/mapper/LatexWebViewMapper.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/latex/view/model/block/BaseStyleBlock.kt
Task: [#ALTAPPS-432](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-432/Android-class-alert-alert-primary-has-incorrect-style-for-dark-theme)
**Reviewers**
- add missing styles for .alert html class
- apply text color to .alert html class
=> ALTAPPS-432: Android fix alert html classes has incorrect style

.github/workflows/gh_pages_analytics.yml, build.gradle.kts, gradle/libs.versions.toml, iosHyperskillApp/Podfile.lock, shared/build.gradle.kts, shared/shared.podspec
[#ALTAPPS-465](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-465)
**Checklist**
- Builds documentation with Dokka
- Adds workflow that builds and deploys analytics documentation to GitHub Pages
=> ALTAPPS-465: Build and Deploy Analytics Documentation to GitHub Pages

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/view/ui/adapter/decoration/CustomDividerItemDecoration.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/topics_repetitions/view/delegate/TopicsRepetitionListDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/topics_repetitions/view/fragment/TopicsRepetitionFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/topics_repetitions/view/model/TopicsRepetitionListItem.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/topics_repetitions/view/model/TopicsRepetitionListState.kt, androidHyperskillApp/src/main/res/layout/item_topics_to_repeat_header.xml, androidHyperskillApp/src/main/res/layout/layout_topics_repetition_topics_list.xml, androidHyperskillApp/src/main/res/values/dimens.xml
[#ALTAPPS-457](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-457)
**Checklist**
- Move topics-to-repeat-list header into recyclerView
- Add topics-from-other tracks rendering in recyclerView
- Implement CustomDividerItemDecoration for conditional dividers
=> ALTTAPPS-457: Android topics from other track for repetition

shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/interactor/StepQuizInteractor.kt
[#ALTAPPS-462](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-462)
**Checklist**
=> ALTAPPS-462: shared polling submission

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/extensions/FragmentSerializableArgumentDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_table/view/fragment/TableColumnSelectionBottomSheetDialogFragment.kt
[#ALTAPPS-420](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-420)
**Checklist**
- Implement delegate to store complex objects in Fragement.arguments
- Use new delegate to store chosenColumns fields
=> ALTAPPS-420: Fix cell serialisation

androidHyperskillApp/src/main/AndroidManifest.xml, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/receiver/AlarmReceiver.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/receiver/BootCompleteReceiver.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/service/BootCompleteService.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/service/NotificationAlarmService.kt
[#ALTAPPS-332](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-)
**Checklist**
- Add missing WAKE-LOCK permisson
- Mark all current android-specific locac-notification infrastructure as Deprecated to replace it with WorkManager in future
=> ALTAPPS-332: Fix android app crash in local notifications

iosHyperskillApp/iosHyperskillApp/Sources/Helpers/HTMLToAttributedStringConverter.swift
[#ALTAPPS-414](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-414)
**Checklist**
- Updates `HTMLToAttributedStringConverter` initializer to use `defaultTagTransformers`
=> ALTAPPS-414: iOS fix choices elements HTML-content rendering (no line breaks)

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_practice/view/fragment/StepPracticeFragment.kt, androidHyperskillApp/src/main/res/layout/view_step_quiz_theory_button.xml, androidHyperskillApp/src/main/res/menu/step_quiz_appbar_menu.xml
[#ALTAPPS-479](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-479/Android-Add-theory-button-on-the-repetitions-quiz-screen)
**Checklist**
Add theory item into StepPracticeFragment's menu
=> ALTAPPS-479: Add theory button on the repetitions quiz screen

androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/track/view/fragment/TrackFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_home.xml, androidHyperskillApp/src/main/res/layout/fragment_track.xml, androidHyperskillApp/src/main/res/layout/layout_home_skeleton.xml, androidHyperskillApp/src/main/res/layout/layout_track_skeleton.xml, androidHyperskillApp/src/main/res/values/dimens.xml
[#ALTAPPS-459](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-459)
**Checklist**
- Add skeleton loading view to HomeFragment and TrackFragment
=> ALTAPPS-459: Replace spiner loading with skeleton on Home and Track screens.

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/injection/AndroidAppComponent.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/injection/AndroidAppComponentImpl.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/image_loading/injection/ImageLoadingComponent.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/image_loading/injection/ImageLoadingComponentImpl.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/placeholder_new_user/dialog/NewUserTrackDetailsBottomSheet.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/placeholder_new_user/fragment/PlaceholderNewUserFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_hints/fragment/StepQuizHintsFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/track/view/fragment/TrackFragment.kt
[#ALTAPPS-534](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-534/Move-ImageLoader-into-AndroidAppComponent-root)
**Checklist**
Use a singleton instance of ImageLoader across application
=> ALTAPPS-534: Move ImageLoade intoAndroidAppComponent root

shared/build.gradle.kts, shared/src/androidMain/kotlin/org/hyperskill/app/step_quiz_hints/mapper/StepQuizHintsViewStateMapper.kt, shared/src/androidTest/kotlin/org/hyperskill/StepQuizHintsViewStateMapperTest.kt
[#ALTAPPS-520](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-520/Android-Hints-crash-NoSuchElementException)
**Checklist**
- Fix viewState mapping
- Add tests
=> ALTAPPS-520: Fix StepQuiz feature crash on android

androidHyperskillApp/build.gradle.kts, gradle/libs.versions.toml, shared/build.gradle.kts, shared/src/androidMain/kotlin/org/hyperskill/app/network/PreconfiguredHttpClient.kt, shared/src/commonMain/kotlin/org/hyperskill/app/network/NetworkBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/network/PreconfiguredHttpClient.kt, shared/src/commonMain/kotlin/org/hyperskill/app/network/injection/NetworkModule.kt, shared/src/iosMain/kotlin/org/hyperskill/app/network/PreconfiguredHttpClient.kt
[#ALTAPPS-552](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-552/Android-Sentry-capture-HTTP-client-errors)
**Checklist**
- Add PreconfiguredHttpClient to create HttpClien on the platform and to be able to configure it for platform needs.
- Add SentryOkHttpInterceptor to Android HttpClient
- Update android centry lib
- Disable auto network capturing on Android
=> ALTAPPS-552: Android Sentry capture HTTP client errors

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_fullscreen_code/dialog/CodeStepQuizFullScreenDialogFragment.kt
[#ALTAPPS-580](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-580)
**Checklist**
- Fix local [CodeStepQuizFullScreenDialogFragment](https://github.com/hyperskill/mobile-app/commit/ea7f2a42adcfdeb3bcb54f7e052754277809a45c) state is not synced with Feature state when reset code
=> ALTAPPS-580: Android fix ResetCode action on CodeStepQuizFullScreenDialogFragment

.github/actions/setup-android/action.yml, .github/actions/setup-ios/action.yml
[#ALTAPPS-614](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-614)
**Checklist**
- Bumps Java from 11 to 17
- Bumps actions/setup-java from 3.6.0 to 3.10.0
=> ALTAPPS-614: GitHub Actions bump Java from 11 to 17

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Helpers/RemoveBackButtonTitleHostingController.swift, iosHyperskillApp/iosHyperskillApp/Sources/Helpers/StyledHostingController.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/StepAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/TopicsRepetitionsAssembly.swift
[#ALTAPPS-601](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-601)
**Checklist**
- Refactor rename `RemoveBackButtonTitleHostingController` -> `StyledHostingController`
- Left-aligned navigation bar title appearance implementation with animation
Usage:
- `StyledHostingController(rootView: rootView, appearance: .withoutBackButtonTitle)`
- `StyledHostingController(rootView: rootView, appearance: .leftAlignedNavigationBarTitle)`.
=> ALTAPPS-601: iOS left aligned navigation bar title appearance

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/View/UIKit/CodeEditorView/CodeEditorView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/View/UIKit/CodeInputAccessory/CodeInputAccessoryBuilder.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/View/UIKit/CodeInputAccessory/Toolbar/CodeInputAccessoryView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/View/UIKit/CodeInputAccessory/Toolbar/PasteControl/CodeInputPasteControl.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/View/UIKit/CodeInputAccessory/Toolbar/PasteControl/OpaqueUIPasteControl.swift
[#ALTAPPS-464](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-464)
**Checklist**
- Adds paste control to the code editor's inputAccessoryView
=> ALTAPPS-464: iOS add paste control to code editor input accessory view

iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/View/UIKit/CodeEditorView/CodeEditorView.swift
[#ALTAPPS-673](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-673)
**Checklist**
Temporarily disables code completion in the code editor because it blocks the main thread. We need more time to investigate this.
=> ALTAPPS-673: iOS code editor disable code completion

.github/workflows/lint.yml, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/injection/AndroidAppComponentImpl.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/gamification_toolbar/view/ui/delegate/GamificationToolbarDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/track/view/fragment/TrackFragment.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/HomeViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Profile/Views/Statistics/ProfileStatisticsItemView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Track/TrackViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Track/Views/DiscoverNext/TopicToDiscoverNextButtonView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/core/injection/AppGraph.kt, shared/src/commonMain/kotlin/org/hyperskill/app/gamification_toolbar/domain/model/GamificationToolbarScreen.kt, shared/src/commonMain/kotlin/org/hyperskill/app/gamification_toolbar/injection/GamificationToolbarComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/gamification_toolbar/presentation/GamificationToolbarActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/gamification_toolbar/presentation/GamificationToolbarFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/gamification_toolbar/presentation/GamificationToolbarReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/injection/HomeComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/sentry/domain/model/transaction/HyperskillSentryTransactionBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/model/Track.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/domain/model/TrackWithProgress.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/injection/TrackComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track/presentation/TrackReducer.kt, shared/src/iosMain/kotlin/org/hyperskill/app/core/injection/AppGraphImpl.kt
[#ALTAPPS-680](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-680)
**Checklist**
- `TrackWithProgress` added into `GamificattionToolbarFeature.State`
- StudyPlan & TopicCompleted subscription added to reload `TrackWithProgress`.
- `GamificattionToolbarScreen` added as a dependency for `GamificattionToolbarActionDispatcher` to use `fetchTrackProgressSentryTransaction` for isolated `TrackWithProgress` loading.
=> ALTAPPS-680: Shared add progress into gamification toolbar

androidHyperskillApp/build.gradle.kts, androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/view/ui/SwipeRefreshExtenions.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/home/view/ui/fragment/HomeFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/track/view/fragment/TrackFragment.kt, androidHyperskillApp/src/main/res/layout/fragment_home.xml, androidHyperskillApp/src/main/res/layout/fragment_profile.xml, androidHyperskillApp/src/main/res/layout/fragment_track.xml, gradle/libs.versions.toml
[#ALTAPPS-535](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-535)
**Checklist**
- SwipeRefreshLayout added as a root element into `Home`, `Track` & `Profile` fragments layouts
- Handle `SwipeRefreshLayout.isRefreshing`
=> ALTAPPS-535: Android add swipeRefresh to Home, Track and Profile fragments

shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/injection/PlaceholderNewUserComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/injection/PlaceholderNewUserFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/placeholder_new_user/presentation/PlaceholderNewUserActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/data/repository/ProfileRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/data/source/ProfileRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/interactor/ProfileInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/Profile.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/repository/ProfileRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/remote/ProfileRemoteDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/remote/model/ProfileSelectTrackRequest.kt
[#ALTAPPS-687](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-687)
**Checklist**
- Turn off project auto selection for new users when freemium feature is enabled
**WTD**
**Summary:**
* **Implemented Freemium Interactor**
Added a new component to manage freemium features for new users
* **Enhanced Profile Repository**
Improved track selection functionality in profile repository and data sources
* **Updated Logic for Track Selection**
Refined the decision-making process based on freemium status for selecting tracks with or without a project
**Poem:**
_In the realm of Mobile, a tale unfurls,_  
_As PlaceholderNewUserComponentImpl swirls._  
_FreemiumInteractor enters, a builder in hand,_  
_To aid ProfileRepositoryImpl, as …
=> ALTAPPS-687: Shared disable project auto selection for new users with freemium

shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StateExtentions.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/view/StudyPlanWidgetViewStateMapper.kt, shared/src/commonTest/kotlin/org/hyperskill/StudyPlanWidgetTest.kt
[#ALTAPPS-714](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-714)
**Checklist**
* **Updated function in firstSection**
Replaced `firstSection()` with `firstVisibleSection()`.
=> ALTAPPS-714: Shared fix study plan reload content in background

shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/view/StudyPlanWidgetViewStateMapper.kt, shared/src/commonTest/kotlin/org/hyperskill/StudyPlanWidgetTest.kt
[#ALTAPPS-715](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-715)
**Checklist**
Fixes section statistics visibility (formatted topics count and time to complete) - should always be visible for first visible section or expanded one
=> ALTAPPS-715: Shared fix study plan section statistics visibility

shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/hyperskill/HyperskillAnalyticPart.kt, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/hyperskill/HyperskillAnalyticTarget.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/analytic/StudyPlanClickedActivityHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/analytic/StudyPlanClickedRetryActivitiesLoadingHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/analytic/StudyPlanClickedRetryContentLoadingHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/analytic/StudyPlanClickedSectionHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/analytic/StudyPlanViewedHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetReducer.kt, shared/src/commonTest/kotlin/org/hyperskill/StudyPlanScreenTest.kt, shared/src/commonTest/kotlin/org/hyperskill/StudyPlanWidgetTest.kt
[#ALTAPPS-710](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-710)
**Checklist**
Adds missing analytic events
=> ALTAPPS-710: Shared study plan analytics

shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/model/StudyPlanSection.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/model/StudyPlanSectionType.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StateExtentions.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/view/StudyPlanWidgetViewStateMapper.kt, shared/src/commonTest/kotlin/org/hyperskill/StudyPlanWidgetTest.kt
[#ALTAPPS-729](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-729)
**Checklist**
Adds study plan sections filtering (display only supported ones):
1. `stage`
2. `extra topics`
3. `root topics`
=> ALTAPPS-729: Shared study plan filter sections

shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetReducer.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/widget/StudyPlanWidgetTest.kt
[#ALTAPPS-786](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-786)
**Checklist**
After successful loading of learning activities for some section we must remove this section if no available learning activities were loaded. If it happens with the current section we also need to expand the next section because after removing the first section the next one becomes the current one and it must be expanded.
=> ALTAPPS-786: Shared fix handling of empty learning activities fetch result for section

androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt
[#ALTAPPS-705](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-705)
**Checklist**
Revert changes with displaying country name because it doesn't fix the problem, but did it worse
=> ALTAPPS-705: Android revert fix of displaying country name

iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/PanModal/PanModalSwiftUIViewController.swift
[#ALTAPPS-838](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-838)
**Checklist**
- Fixes `PanModalSwiftUIViewController`
=> ALTAPPS-838: iOS fix streak recovery modal didn't appear for the first application run

androidHyperskillApp/src/main/java/org/hyperskill/app/android/HyperskillApp.kt, iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Extensions/Shared/Model/BuildVariant+Current.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/Core/Injection.swift, iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/ApplicationInfo.swift, iosHyperskillApp/iosHyperskillApp/Sources/Systems/Sentry/SentryManager.swift, shared/src/commonMain/kotlin/org/hyperskill/app/core/domain/BuildVariant.kt
[#ALTAPPS-843](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-843)
**Checklist**
1. Adds `internalRelease` env in iOS
2. Updates providing the current `BuildVariant` in Android to shared
=> ALTAPPS-843: iOS Sentry add internalRelease environment

iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/AppViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/App/ViewControllers/AppViewController.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Onboarding/OnboardingView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Onboarding/OnboardingViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProfileSettings/ProfileSettingsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/ProfileSettings/ProfileSettingsViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StageImplement/StageImplementViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StageImplement/Views/StageImplementView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/StepViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/StepQuizViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/StepQuizHintsViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/Views/StepQuizHintsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/TopicsRepetitionsViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/TopicsRepetitions/Views/TopicsRepetitionsView.swift
[#ALTAPPS-847](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-847)
**Checklist**
Updates initial data loading for features - moves to view model init.
Tab bar modules (Home, Study Plan, Profile) don't change, because for those screens we want to load data when a tab bar item is active.
=> ALTAPPS-847: iOS update features initial data loading

gradle/libs.versions.toml
[#ALTAPPS-860](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-860)
**Checklist**
Bumps `gradle-versions-plugin` from `0.39.0` to `0.47.0`
=> ALTAPPS-860: Shared bump gradle-versions-plugin from 0.39.0 to 0.47.0

shared/src/iosMain/kotlin/org/hyperskill/app/network/PreconfiguredHttpClient.kt
[#ALTAPPS-885](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-885)
**Checklist**
- Sets the default value for the `timeoutIntervalForRequest` of the Darwin engine
=> ALTAPPS-885: Shared Darwin engine set timeoutIntervalForRequest

androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/local/DailyStudyReminderLocalNotificationDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt
[#ALTAPPS-890](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-890)
**Checklist**
The root cause of this bug are race-conditions. The `ProfileFragment` send messages which should save the availability flag or reminder time in the settings, but these operations are asynchronous. So, `DailyStudyReminderLocalNotificationDelegate` access the data before they are updated via actionDispatcher. 
I've removed the `notificationInteractor` access from `DailyStudyReminderLocalNotificationDelegate` in case of notification planning from the `ProfileFragment`.
=> ALTAPPS-890: Fix Android daily reminder

androidHyperskillApp/src/main/java/org/hyperskill/app/android/core/extensions/NotificationExtensions.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/dialog/RequestDailyStudyReminderDialogFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt
[#ALTAPPS-922](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-922)
**Checklist**
- Wrap dailyStudyReminder request dialog with DialogFragment to make it cancelled with the parent fragment
- Make safe access to the context in the callback
=> ALTAPPS-922: Android app crash just after setting reminder from dialog

iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/HomeAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/HomeViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Home/Views/HomeView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/StepQuizAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/StepQuizViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/StudyPlanViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/Views/StudyPlanView.swift
[#ALTAPPS-938](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-938)
[#ALTAPPS-939](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-939)
**Checklist**
- Revert changes of hiding problems limit widget
- Hide "Continue learning in web" button on home screnn
=> ALTAPPS-938, ALTAPPS-939: IOS show problem limit widget and hide go to web button on home screen

iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizHints/Views/StepQuizHintCardView.swift, shared/src/commonMain/resources/MR/base/strings.xml
[#ALTAPPS-945](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-945)
**Checklist**
- Make step quiz hint text copyable on iOS
=> ALTAPPS-945: iOS make step quiz hint text copyable

androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification/permission/NotificationPermissionDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/notification_onboarding/fragment/NotificationsOnboardingFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/profile/view/fragment/ProfileFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step/view/delegate/StepDelegate.kt
[ALTAPPS-992](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-992)
**Checklist**
In case the system disable the permission dialog - open the permissions settings screen, to allow a user to give the notification permission
=> ALTAPPS-992: Show permission settings screen if permission dialog is not showed

iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCode/ViewData/StepQuizCodeViewData.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCode/ViewData/StepQuizCodeViewDataMapper.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCode/Views/StepQuizCodeEditorView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCode/Views/StepQuizCodeView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCodeFullScreen/StepQuizCodeFullScreenAssembly.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizPyCharm/StepQuizPyCharmView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizPyCharm/StepQuizPyCharmViewDataMapper.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizSQL/StepQuizSQLViewDataMapper.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizSQL/Views/StepQuizSQLView.swift
[#ALTAPPS-949](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-949)
**Checklist**
Uses code language name from `shared` in `StepQuizCodeEditorView`
=> ALTAPPS-949: iOS StepQuizCodeEditorView use language name from shared

shared/src/commonMain/kotlin/org/hyperskill/app/home/presentation/HomeActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/progress_screen/presentation/ProgressScreenActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project_selection/list/presentation/ProjectSelectionListActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/sentry/domain/SentryExtentions.kt
[ALTAPPS-544](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-544)
**Checklist**
- Implement `SentryInteractor.withTransaction` extension to automatically start and finish a transaction
=> ALTAPPS-544: Shared Sentry transactions convenient API

shared/src/commonMain/kotlin/org/hyperskill/app/freemium/domain/interactor/FreemiumInteractor.kt
[#ALTAPPS-999](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-999)
**Checklist**
The problem of previous solution was necessity to do network request in scope of feature that could be destroyed before that request is done (for example tap back button right after solving problem and user will see not updated limits on study plan screen). The easiest solution I seen - hardcode increasing limits like it's done on [backend](https://github.com/hyperskill/alt/blob/251f0c2cd27b048d3a8936b2f6913d592a651512/apps/freemium/constants.py#L47)
Another argument is that updating of limits on backend happens asynchronously - it means that if we want to add loading from backend we can face with not actual state of subscription from backend …
=> ALTAPPS-999: Shared update limits locally instead of loading from backend

androidHyperskillApp/src/main/res/layout/layout_fill_blanks_skeleton.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_fill_blanks_binding.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_parsons.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_sorting.xml, androidHyperskillApp/src/main/res/layout/layout_step_quiz_text.xml, androidHyperskillApp/src/main/res/values/dimens.xml
[#ALTAPPS-1029](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1029)
**Checklist**
- Add missing horizontal margin to step quizzes
- Fix fill-in-the-blanks layout relative to the hints
=> ALTAPPS-1029: Android fix android step quiz horizontal margin

iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Views/SwiftUI/PlaceholderView/PlaceholderView+Configurations.swift
Use local presentation mode for step error placeholder view when it's parent is stage implement.
[#ALTAPPS-725](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-725)
**Checklist**
Use `PlaceholderView.Configuration.PresentationMode.local` for step error placeholder view when it's parent is stage implement
=> ALTAPPS-725: iOS fix stage implement step error placeholder

.github/workflows/automerge_into_release.yml
Fixes retrieving the latest tag in the repository.
Sort by the date of the commit associated with each tag, and then removes the first character from the tag name.
=> GitHub Actions: Automerge fix get current version number

.github/actions/setup-ios/action.yml
Disables dependents upgrade of `git-crypt` by setting `HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK`
=> GitHub Actions: Setup iOS disable dependents upgrade of git-crypt

.github/workflows/android_beta_deployment.yml, .github/workflows/ios_beta_deployment.yml
1. Disables concurrency (cancel in progress) for `iOS Beta Deployment` and `Android Beta Deployment`
2. If automerge merged smh into current release branch, active beta deployment will not be cancelled
=> GitHub Actions: Disable concurrency for beta deployments

iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizFillBlanks/Views/FillBlanksQuizViewWrapper.swift
[#ALTAPPS-1062](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1062)
**Checklist**
- Fixes incorrect collection view layout on first update
=> ALTAPPS-1062: iOS fix fill blanks with selects code block is clipped

androidHyperskillApp/src/main/java/org/hyperskill/app/android/sentry/domain/model/manager/SentryManagerImpl.kt, iosHyperskillApp/iosHyperskillApp/Sources/Systems/Sentry/SentryManager.swift, shared/src/commonMain/kotlin/org/hyperskill/app/logging/presentation/WrapWithLogger.kt
**Checklist**
- Disable sentry debug logs to not have sentry internal logs.
=> Shared: Disable Sentry debug logs

androidHyperskillApp/src/main/java/org/hyperskill/app/android/code/util/CodeEditorKeyboardExtensionUtil.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/code/view/widget/CodeEditorLayout.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_code/view/fragment/CodeStepQuizFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_fullscreen_code/dialog/CodeStepQuizFullScreenDialogFragment.kt
[ALTAPPS-1088](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1088)
**Checklist**
- Sync fullscreen code editor code before sending toolbar symbol analytics event
=> ALTAPPS-1088: Android fix toolbar symbols insert into codeEditor

shared/src/commonMain/kotlin/org/hyperskill/app/logging/presentation/WrapWithLogger.kt
**Checklist**
- Set state logs severity of Debug, to not send them to Sentry (fix after #808)
=> Shared: Set state logs severity of Debug

.github/PULL_REQUEST_TEMPLATE.md, shared/src/commonMain/kotlin/org/hyperskill/app/auth/remote/model/AuthResponse.kt, shared/src/commonMain/kotlin/org/hyperskill/app/devices/domain/model/Device.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/Profile.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/domain/model/ProfileSettings.kt, shared/src/commonTest/kotlin/org/hyperskill/auth/AuthResponseSerializationTest.kt, shared/src/commonTest/kotlin/org/hyperskill/device/DeviceSerializationTest.kt, shared/src/commonTest/kotlin/org/hyperskill/profile/ProfileSerializationTest.kt, shared/src/commonTest/kotlin/org/hyperskill/profile/cache/ProfileSerializationTest.kt, shared/src/commonTest/kotlin/org/hyperskill/profile_settings/ProfileSettingsSerializationTest.kt
[ALTAPPS-1072](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1072)
**Checklist**
- Add docs and serialization test for: `Profile`,  `ProfileSettings`, `Device`, `AuthResponse` models
=> ALTAPPS-1072: Shared protect app from errors due to cache models serialization

shared/src/commonMain/kotlin/org/hyperskill/app/main/presentation/AppFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/main/presentation/AppReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/streak_recovery/presentation/StreakRecoveryActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/streak_recovery/presentation/StreakRecoveryFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/streak_recovery/presentation/StreakRecoveryReducer.kt, shared/src/commonTest/kotlin/org/hyperskill/streak_recovery/StreakRecoveryTest.kt, shared/src/commonTest/kotlin/org/hyperskill/streaks/domain/model/StreakStub.kt
[#ALTAPPS-836](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-836)
**Checklist**
- Fixes incorrect behavior on streak recovery `first-time offer` that costs `0` gems
=> ALTAPPS-836: Shared fix gems are decreased but streak recovery cost is 0 for the first time

.github/workflows/android_beta_deployment.yml, .github/workflows/android_deploy_to_firebase_manually.yml, androidHyperskillApp/fastlane/Fastfile
1. Fixes issue with #871
2. Adds `inherit` keyword to implicitly pass the secrets to reusable workflows
=> GitHub Actions: Fix deploy Android manually to Firebase App Distribution

.github/actions/setup-android/action.yml, .github/actions/setup-ios/action.yml, .github/workflows/automerge_into_release.yml, .github/workflows/build_caches.yml, .github/workflows/ci.yml, .github/workflows/ios_beta_deployment.yml, .github/workflows/ios_release_deployment.yml, .github/workflows/ios_unit_testing.yml
1. Upgrades to the new [M1 macOS runner](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/)
2. Bumps ruby/setup-ruby from 1.170.0 to 1.171.0 ([Add support for macos-14 GitHub runners](https://github.com/ruby/setup-ruby/releases/tag/v1.171.0))
=> GitHub Actions: Bump macOS runner from 13 to 14

iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/ContentProcessor/Processing/ContentProcessingInjection.swift, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/ContentProcessor/Processing/ContentProcessor.swift
[#ALTAPPS-1104](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1104)
**Checklist**
- Adds `DataMobileHiddenElementsInjection` that removes all elements that are marked as hidden on mobile devices
=> ALTAPPS-1104: iOS remove elements with the attribute data-mobile-hidden

androidHyperskillApp/src/main/java/org/hyperskill/app/android/HyperskillApp.kt, shared/src/androidMain/kotlin/org/hyperskill/app/purchases/domain/AndroidPurchaseManager.kt, shared/src/commonMain/kotlin/org/hyperskill/app/purchases/domain/interactor/PurchaseInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/purchases/domain/model/PurchaseManager.kt, shared/src/iosMain/kotlin/org/hyperskill/app/purchase/domain/model/IOSPurchaseManager.kt
[ALTAPPS-1152](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1152)
**Checklist**
- Configure RevenueCat only with user id
=> ALTAPPS-1152: Shared setup RevenueCat only when user is authorized

iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/Model/Analyze/CodePlaygroundManager.swift
[#ALTAPPS-638](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-638)
**Checklist**
- Fixes issue with code editor not replaces symbols in selection
=> ALTAPPS-638: iOS fix code editor not replaces symbols in selection

shared/src/commonMain/kotlin/org/hyperskill/app/progress_screen/presentation/ProgressScreenActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/project_selection/details/domain/interactor/ProjectSelectionDetailsInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/details/presentation/TrackSelectionDetailsActionDispatcher.kt
[#ALTAPPS-1158](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1158)
**Checklist**
1. Fixes crash related with `TrackSelectionDetailsActionDispatcher` and it's `InternalAction.FetchAdditionalInfo` action handling
=> ALTAPPS-1158: Shared fix track selection details screen crashes

androidHyperskillApp/src/main/java/org/hyperskill/app/android/paywall/fragment/PaywallFragment.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/injection/StepQuizComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/injection/StepQuizFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizReducer.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz/StepQuizTest.kt
[#ALTAPPS-1148](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1148)
**Checklist**
- Navigate back after subscription purchase from problems limit bottom sheet
- Subscribe on subscripitn changes to hide problems limit bottom sheet comming back to the step screen with bought subscription
=> ALTAPPS-1148: Shared navigate user back to step after the subscription purchase

shared/src/commonMain/kotlin/org/hyperskill/app/topics_repetitions/data/repository/TopicsRepetitionsRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics_repetitions/data/source/TopicsRepetitionsRemoteDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics_repetitions/domain/interactor/TopicsRepetitionsInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics_repetitions/domain/repository/TopicsRepetitionsRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/topics_repetitions/remote/TopicsRepetitionsRemoteDataSourceImpl.kt
[#ALTAPPS-1182](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1182)
**Checklist**
- Use `is_in_current_track` param in `/api/topics-repetition` and `/api/topics-repetition/statistics`
=> ALTAPPS-1182: Shared support is_in_current_track in topics repetitions

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_theory/view/fragment/StepTheoryFragment.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/StepViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepTheoryContentView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/step_completion/domain/analytic/StepCompletionClickedStartPracticingHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_completion/domain/analytic/StepCompletionHyperskillAnalyticParams.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_completion/presentation/StepCompletionFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_completion/presentation/StepCompletionReducer.kt, shared/src/commonTest/kotlin/org/hyperskill/step_completion/StepCompletionTest.kt
[#ALTAPPS-1196](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1196)
**Checklist**
- Adds `is_located_at_beginning` flag to the start practicing button click event
=> ALTAPPS-1196: Add difference in analytical event for start practicing button

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/PrivacyInfo.xcprivacy
[#ALTAPPS-1199](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1199)
**Checklist**
- Adds `PrivacyInfo.xcprivacy `
=> ALTAPPS-1199: iOS describe use of required reason API in privacy manifests

iosHyperskillApp/iosHyperskillApp/Sources/Modules/Step/Views/StepTheoryContentView.swift
[#ALTAPPS-1220](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1220)
**Checklist**
- Moves start practicing button to bottom safeAreaInset
=> ALTAPPS-1220: iOS stick start practicing button to bottom in theory

shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/processor/AmplitudeAnalyticEventMapper.kt, shared/src/commonTest/kotlin/org/hyperskill/analytic/domain/processor/AmplitudeAnalyticEventMapperTest.kt
[#ALTAPPS-1233](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1233)
**Checklist**
- Adds route path string to AmplitudeAnalyticEvent name for view events ([comment](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1233/Shared-Amplitude-analytic-tool-integration#focus=Comments-74-291687.0-0))
=> ALTAPPS-1233: Shared AmplitudeAnalyticEventMapper update getType for VIEW events

.github/workflows/android_beta_deployment.yml, .github/workflows/android_deploy_to_firebase.yml, .github/workflows/android_deploy_to_firebase_manually.yml, .github/workflows/android_release_deployment.yml, .github/workflows/automerge_into_release.yml, .github/workflows/build_caches.yml, .github/workflows/ci.yml, .github/workflows/cleanup_pr_caches.yml, .github/workflows/codeql.yml, .github/workflows/detect_changed_files_reusable_workflow.yml, .github/workflows/gh_pages_analytics.yml, .github/workflows/ios_beta_deployment.yml, .github/workflows/ios_release_deployment.yml, .github/workflows/ios_unit_testing.yml, .github/workflows/merge_main_into_develop.yml
Bumps [actions/checkout](https://github.com/actions/checkout) from 4.1.1 to 4.1.4.
- [Release notes](https://github.com/actions/checkout/releases)
- [Changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- [Commits](https://github.com/actions/checkout/compare/v4.1.1...v4.1.4)
=> GitHub Actions: Bump actions/checkout from 4.1.1 to 4.1.4

.github/actions/setup-android/action.yml, .github/actions/setup-ios/action.yml, .github/workflows/automerge_into_release.yml, .github/workflows/ci.yml
Bumps [ruby/setup-ruby](https://github.com/ruby/setup-ruby) from 1.171.0 to 1.175.1.
- [Release notes](https://github.com/ruby/setup-ruby/releases)
- [Commits](https://github.com/ruby/setup-ruby/compare/v1.171.0...v1.175.1)
=> GitHub Actions: Bump ruby/setup-ruby from 1.171.0 to 1.175.1

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp.xcodeproj/xcshareddata/xcbaselines/2C919DEC27EEF5BC0022A2F2.xcbaseline/ADDDB70F-EE79-4C0E-9923-72C0A4A25AEF.plist, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/Model/Analyze/CodePlaygroundManager.swift, iosHyperskillApp/iosHyperskillAppTests/FrameworksTests/CodeEditor/CodePlaygroundManager/CodePlaygroundShouldMakeTabLineAfterPerformanceTests.swift
**Checklist**
- Optimizes `shouldMakeTabLineAfter(symbol:language:)`
- The optimized function groups languages by common behavior, reducing the complexity and potentially improving the compiler's ability to optimize the code
=> ALTAPPS-637: iOS optimize shouldMakeTabLineAfter

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp.xcodeproj/xcshareddata/xcbaselines/2C919DEC27EEF5BC0022A2F2.xcbaseline/ADDDB70F-EE79-4C0E-9923-72C0A4A25AEF.plist, iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/Model/Analyze/CodePlaygroundManager.swift, iosHyperskillApp/iosHyperskillAppTests/FrameworksTests/CodeEditor/CodePlaygroundManager/CodePlaygroundManagerCountTabSizePerformanceTests.swift, iosHyperskillApp/iosHyperskillAppTests/FrameworksTests/CodeEditor/CodePlaygroundManager/CodePlaygroundManagerCountTabSizeTests.swift
**Checklist**
- Optimizes `countTabSize(text:)`
- Simplifying Logic: The use of `prefix(while:)` directly counts leading spaces without manually iterating over each character. This not only cleans up the code but should improve performance by utilizing Swift's optimized string handling.
- This approach should lead to faster performance, especially with large text inputs.
=> ALTAPPS-637: iOS CodePlaygroundManager optimize countTabSize(text:)

config/detekt/baseline.xml, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizMatching/StepQuizMatchingView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizMatching/StepQuizMatchingViewData.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizMatching/StepQuizMatchingViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizSorting/StepQuizSortingViewModel.swift, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/domain/validation/StepQuizReplyValidator.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/submissions/domain/model/Reply.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz/domain/validation/StepQuizReplyValidatorTest.kt
[#ALTAPPS-1258](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1258)
**Checklist**
- Don't assign a default option for a matched item if the reply doesn't specify an order for it
=> ALTAPPS-1258: iOS display matching problem as table remove default ordering when reply is missing

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_fill_blanks/delegate/FillBlanksStepQuizFormDelegate.kt, androidHyperskillApp/src/main/res/layout/item_step_quiz_fill_blanks_select_option.xml
[ALTAPPS-1257](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1257)
**Checklist**
- Replace `FlexboxItemDecoration` with a plain margin on each fill blanks item to avoid spacing issues.
=> ALTAPPS-1257: Android fix fill blanks options spacing

shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeatureKeys.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeaturesMap.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/injection/StepComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/injection/StepFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step/presentation/StepActionDispatcher.kt
[#ALTAPPS-1266](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1266)
**Checklist**
- Removes short theory experiment source code
=> ALTAPPS-1266: Shared remove short theory experiment

androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/fragment/StudyPlanFragment.kt, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/StudyPlanViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/Views/StudyPlanView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/core/injection/AppGraph.kt, shared/src/commonMain/kotlin/org/hyperskill/app/core/injection/BaseAppGraph.kt, shared/src/commonMain/kotlin/org/hyperskill/app/sentry/domain/model/transaction/HyperskillSentryTransactionBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/analytic/StudyPlanClickedChangeTrackHyperskillAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/screen/presentation/StudyPlanScreenFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/screen/presentation/StudyPlanScreenReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/details/cache/TrackSelectionDetailsCacheDataSourceImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/details/cache/TrackSelectionDetailsCacheKeyValues.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/details/data/repository/TrackSelectionDetailsRepositoryImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/details/data/source/TrackSelectionDetailsCacheDataSource.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/details/domain/repository/TrackSelectionDetailsRepository.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/details/injection/TrackSelectionDetailsComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/details/injection/TrackSelectionDetailsDataComponent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/details/injection/TrackSelectionDetailsDataComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/details/injection/TrackSelectionDetailsFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/details/presentation/TrackSelectionDetailsActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/list/injection/TrackSelectionListComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/list/injection/TrackSelectionListFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/list/presentation/TrackSelectionListActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/list/presentation/TrackSelectionListFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/list/presentation/TrackSelectionListReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/track_selection/list/view/TrackSelectionListViewStateMapper.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/screen/StudyPlanScreenTest.kt, shared/src/commonTest/kotlin/org/hyperskill/track_selection/TrackProgressStub.kt, shared/src/commonTest/kotlin/org/hyperskill/track_selection/TrackWithProgressStub.kt, shared/src/commonTest/kotlin/org/hyperskill/track_selection/list/TrackSelectionListTest.kt
[#ALTAPPS-1290](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1290)
**Checklist**
1. Adds `StudyPlanScreenFeature.Message.ChangeTrackButtonClicked` and `StudyPlanScreenFeature.Action.ViewAction.NavigateTo.TrackSelectionScreen`
2. Adds `TrackSelectionDetailsDataComponent` to store tracks selection counts
3. Updates the track list sorting in `TrackSelectionListViewStateMapper`
=> ALTAPPS-1290: Shared, iOS improve track switching flow

androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/delegate/StudyPlanWidgetDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/model/StudyPlanRecyclerItem.kt, androidHyperskillApp/src/main/res/layout/item_study_plan_load_more_button.xml, androidHyperskillApp/src/main/res/values/styles.xml, config/detekt/baseline.xml, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/Views/Section/StudyPlanSectionView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/hyperskill/HyperskillAnalyticTarget.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/Profile.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_completion/presentation/MainStepCompletionActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/analytic/StudyPlanAnalyticKeys.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/analytic/StudyPlanLoadMoreActivitiesClickedHSAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/model/StudyPlanSection.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StateExtentions.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetStateExtensions.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/view/mapper/StudyPlanWidgetViewStateMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/view/model/StudyPlanWidgetViewState.kt, shared/src/commonMain/moko-resources/base/strings.xml, shared/src/commonTest/kotlin/org/hyperskill/learning_activities/domain/model/LearningActivityStub.kt, shared/src/commonTest/kotlin/org/hyperskill/profile/ProfileStub.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/domain/model/StudyPlanSectionStub.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/domain/model/StudyPlanSectionTest.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/screen/StudyPlanScreenTest.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/widget/StudyPlanWidgetStateExtensionsTest.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/widget/StudyPlanWidgetTest.kt
[ALTAPPS-1301](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1301)
**Checklist**
- Add `StudyPlanWidgetFeature.State.getActivitiesToBeLoaded` & `StudyPlanSection.getActivitiesToBeLoaded` to determine which activities are still not loaded;
- Add `StudyPlanWidgetFeature.Message.LoadMoreActivitiesClicked`;
- Add `isNextPageLoadingShowed` & `isLoadAllTopicsButtonShown` to the `StudyPlanWidgetViewState.SectionContent.Content`;
- Split `StudyPlanWidgetFeature.ContentStatus` to `StudyPlanWidgetFeature.SectionStatus` & `StudyPlanWidgetViewState.SectionContentStatus`; add `FIRST_PAGE_LOADING` `NEXT_PAGE_LOADING`, `PAGE_LOADED`, `ALL_PAGES_LOADED` to describe pages loading;
- Remove replacing old section activities with new loaded …
=> ALTAPPS-1301: Shared, Android root topics section pagination

androidHyperskillApp/src/main/java/org/hyperskill/app/android/gamification_toolbar/view/ui/delegate/GamificationToolbarDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/fragment/StudyPlanFragment.kt, androidHyperskillApp/src/main/res/layout/layout_gamification_toolbar.xml, gradle/app.versions.toml
**Checklist**
Fix home screen in not shown:
- Fix assigning dimen resource identifier ( instead of reading) to the collapsibleToolbarLayout height;
- Fix change track icon is visible on the leaderboard screen.
=> Hotfix 1.65.1

iosHyperskillApp/iosHyperskillApp/Sources/Extensions/Shared/Model/ReplyExtensions.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCode/StepQuizCodeViewModel.swift, shared/src/commonMain/kotlin/org/hyperskill/app/submissions/domain/model/Reply.kt, shared/src/commonTest/kotlin/org/hyperskill/ReplySerializationTest.kt
[#ALTAPPS-1308](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1308)
**Checklist**
1. Adds `"lint_profile": null` in the reply for code problems.
2. Our JSON configuration does not encode defaults ([code](https://github.com/hyperskill/mobile-app/blob/1b9e0c497e33cc06fff6ec3d77e8c9389ea9d098/shared/src/commonMain/kotlin/org/hyperskill/app/network/injection/NetworkModule.kt#L17), [docs](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-json/kotlinx.serialization.json/-json-configuration/encode-defaults.html)), so I made `Reply.lintProfile` with a `String?` type and a default value of an empty string to be able to serialize `null`.
=> ALTAPPS-1308: Shared speed up code submissions evaluation for beginners by removing linters

shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/presentation/ProfileSettingsReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile_settings/view/ProfileSettingsViewStateMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/subscriptions/domain/model/SubscriptionType.kt
[ALTAPPS-1317](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1317)
**Checklist**
- Add `SubscriptionType.canUpgradeToMobileOnly` flag;
- Update subscription management conditions in `ProfileSettingsViewStateMapper` & `ProfileSettingsReducer.handleSubscriptionDetailsClicked`.
=> ALTAPPS-1317: Shared fix subscription management is not available for MobileContentTrial subscription

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz_matching/view/delegate/MatchingStepQuizFormDelegate.kt, shared/src/commonMain/kotlin/org/hyperskill/app/comments/screen/presentation/CommentsScreenReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/core/utils/CollectionExtensions.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/domain/model/CodeBlock.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksStateExtensions.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_fill_blanks/presentation/FillBlanksItemMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetReducer.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/StepQuizCodeBlanksReducerTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/StepQuizCodeBlanksStateExtensionsTest.kt
[#ALTAPPS-1318](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1318)
**Checklist**
1. Updates `SuggestionClicked` logic for the `Variable` code block to automatically select the next unselected child.
2. Adds a `# solved with code blanks` comment to the reply.
=> ALTAPPS-1318: Shared code blanks variable block type improvements

iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthSocial/AuthSocialViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthSocial/Views/AuthSocialControlsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/AuthSocial/Views/AuthSocialView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Services/Auth/Social/SocialAuthService.swift, shared/src/commonMain/moko-resources/base/strings.xml
[#ALTAPPS-1327](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1327)
**Checklist**
- Adds "More options" button
=> ALTAPPS-1327: iOS hide JetBrains and GitHub social providers with additional tap

shared/src/commonMain/kotlin/org/hyperskill/app/notification/local/cache/NotificationCacheKeyValues.kt, shared/src/commonMain/kotlin/org/hyperskill/app/notifications_onboarding/presentation/NotificationsOnboardingFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/root/presentation/WelcomeOnboardingFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/root/presentation/WelcomeOnboardingReducer.kt, shared/src/commonTest/kotlin/org/hyperskill/notifications_onboarding/NotificationsOnboardingFeatureTest.kt
[#ALTAPPS-1328](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1328)
**Checklist**
1. Skip programming language selection, redirect to Python track directly after questionnaire
2. Set default notifications onboarding hour to current hour
=> ALTAPPS-1328: Shared Aug 2024 ads campaigns onboarding improvements

iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuizSubmodules/StepQuizCodeBlanks/Views/StepQuizCodeBlanksSuggestionsView.swift
[#ALTAPPS-1341](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1341)
**Checklist**
- Fixes incorrect code blanks step 47913 rendering by preserving height to avoid layout jumps when no suggestions.
=> ALTAPPS-1341: iOS fix incorrect code blanks step 47913 rendering

androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/delegate/StudyPlanWidgetDelegate.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/mapper/StudyPlanWidgetUIStateMapper.kt, androidHyperskillApp/src/main/java/org/hyperskill/app/android/study_plan/model/StudyPlanRecyclerItem.kt, androidHyperskillApp/src/main/res/drawable/ic_study_plan_expand_all.xml, androidHyperskillApp/src/main/res/layout/item_study_plan_activity.xml, androidHyperskillApp/src/main/res/layout/item_study_plan_expand_completed_button.xml, androidHyperskillApp/src/main/res/values/dimens.xml, config/detekt/baseline.xml, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StudyPlan/Views/Section/StudyPlanSectionView.swift, shared/src/commonMain/kotlin/org/hyperskill/app/analytic/domain/model/hyperskill/HyperskillAnalyticTarget.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/domain/analytic/StudyPlanExpandCompletedActivitiesClickedHSAnalyticEvent.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/MainStudyPlanWidgetActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/presentation/StudyPlanWidgetStateExtensions.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/view/mapper/StudyPlanWidgetViewStateMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/study_plan/widget/view/model/StudyPlanWidgetViewState.kt, shared/src/commonMain/moko-resources/base/strings.xml, shared/src/commonTest/kotlin/org/hyperskill/study_plan/screen/StudyPlanScreenTest.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/widget/StudyPlanExpandCompletedActivitiesTest.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/widget/StudyPlanLoadMoreActivitiesTest.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/widget/StudyPlanWidgetStateExtensionsTest.kt, shared/src/commonTest/kotlin/org/hyperskill/study_plan/widget/StudyPlanWidgetTest.kt
[ALTAPPS-1335](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1335)
**Checklist**
- Update `StudyPlanWidgetFeature.State.getNextRootTopicsActivitiesToBeLoaded` so that only activities after last loaded activity are taken;
- Implement `StudyPlanWidgetFeature.State.getActivitiesBeforeCurrentActivityToBeLoaded` to get unloaded activities before current activity;
- Add `StudyPlanWidgetFeature.Message,ExpandCompletedActivitiesClicked` to signal about `Expand completed` button is clicked;
- Replace `StudyPlanWidgetFeature.StudyPlanSectionInfo.sectionContentStatus` with separated content status for the main page, next page and completed page;
- Pass `StudyPlanWidgetFeature.SectionPage` into …
=> ALTAPPS-1335: Shared, Android support skipped and completed studyplan activities

iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Models/Constants/Strings.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/PaywallViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/Views/Content/PaywallContentView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/Views/Content/PaywallFeaturesView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/Views/Content/PaywallFooterView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/Views/Content/PaywallSubscriptionProductsView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/Paywall/Views/PaywallView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Systems/PurchaseManager.swift, shared/src/androidMain/kotlin/org/hyperskill/app/purchases/domain/AndroidPurchaseManager.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallActionDispatcher.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/presentation/PaywallFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/paywall/view/PaywallViewStateMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/purchases/domain/interactor/PurchaseInteractor.kt, shared/src/commonMain/kotlin/org/hyperskill/app/purchases/domain/model/PurchaseManager.kt, shared/src/commonMain/moko-resources/base/strings.xml, shared/src/iosMain/kotlin/org/hyperskill/app/purchases/domain/manager/IosPurchaseManager.kt, shared/src/iosMain/kotlin/org/hyperskill/app/purchases/domain/manager/IosPurchaseManagerImpl.kt
[#ALTAPPS-1345](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1345)
**Checklist**
- Adds support for annual subscription plan on iOS
=> ALTAPPS-1345: iOS mobile only subscription annual plan

iosHyperskillApp/iosHyperskillApp/Sources/Extensions/Shared/Model/BlockOptionsExtensions.swift, shared/src/commonMain/kotlin/org/hyperskill/app/step/domain/model/Block.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/domain/model/template/CodeBlanksTemplateMapper.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksResolver.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz_code_blanks/presentation/StepQuizCodeBlanksStateExtensions.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducerElifAndElseStatementsSuggestionsAvailabilityTest.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz_code_blanks/presentation/StepQuizCodeBlanksReducerInitializeTest.kt
[#ALTAPPS-1346](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1346)
**Checklist**
- Adds support for `code_blanks_available_conditions` step block option
=> ALTAPPS-1346: Shared, iOS code blanks support code_blanks_available_conditions

androidHyperskillApp/src/main/java/org/hyperskill/app/android/step_quiz/view/fragment/DefaultStepQuizFragment.kt, config/detekt/baseline.xml, iosHyperskillApp/iosHyperskillApp.xcodeproj/project.pbxproj, iosHyperskillApp/iosHyperskillApp/Sources/Extensions/SwiftUI/View/View+OnTapWhenDisabled.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/StepQuizViewModel.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizActionButtons/StepQuizActionButtons.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizActionButtons/StepQuizRetryButton.swift, iosHyperskillApp/iosHyperskillApp/Sources/Modules/StepQuiz/Views/StepQuizView.swift, iosHyperskillApp/iosHyperskillApp/Sources/Views/SwiftUI/Effects/BounceEffect.swift, iosHyperskillApp/iosHyperskillApp/Sources/Views/SwiftUI/Effects/JiggleEffect.swift, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/step_quiz/presentation/StepQuizReducer.kt, shared/src/commonTest/kotlin/org/hyperskill/step_quiz/StepQuizTest.kt
[#ALTAPPS-1350](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1350)
**Checklist**
- Adds a bouncing animation to the retry button when the user taps on the quiz UI while it is disabled
=> ALTAPPS-1350: iOS clarify reset necessity for users

shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeatureKeys.kt, shared/src/commonMain/kotlin/org/hyperskill/app/profile/domain/model/FeaturesMap.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/root/presentation/WelcomeOnboardingReducer.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/track_details/injection/WelcomeOnboardingTrackDetailsComponentImpl.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/track_details/injection/WelcomeOnboardingTrackDetailsFeatureBuilder.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/track_details/presentation/WelcomeOnboardingTrackDetailsFeature.kt, shared/src/commonMain/kotlin/org/hyperskill/app/welcome_onboarding/track_details/presentation/WelcomeOnboardingTrackDetailsReducer.kt
Reverts hyperskill/mobile-app#1181, [ALTAPPS-1361](https://vyahhi.myjetbrains.com/youtrack/issue/ALTAPPS-1361)
=> Revert "ALTAPPS-1356: Shared Python adopted course selection"

iosHyperskillApp/fastlane/metadata/en-US/privacy_url.txt, shared/src/commonMain/moko-resources/base/strings.xml
**Checklist**
Resolves #1206
This pull request includes updates to URLs for the privacy policy across several files to ensure consistency and correctness.
URL updates:
* [`iosHyperskillApp/fastlane/metadata/en-US/privacy_url.txt`](diffhunk://#diff-4cb19512a8760b5a1614269202362da29045ca3b615e25a4f88970ed10dea50eL1-R1): Updated the privacy policy URL to `https://hyperskill.org/terms` from the old URL.
* [`shared/src/commonMain/moko-resources/base/strings.xml`](diffhunk://#diff-a5d29234576a56f04e85e7bf159fdf7a31bb65562c058ff638df3dcf049859f5L338-R338): Updated the `settings_privacy_policy_url` and `paywall_tos_and_privacy_url` to the new URL `https://hyperskill.org/terms` for consistency. [[1]](diffhunk://#diff-a5d29234576a56f04e85e7bf159fdf7a31bb65562c05 …
=> Update privacy policy URLs

iosHyperskillApp/iosHyperskillApp/Info.plist
**Checklist**
Resolves #1210 
This pull request includes a small but important change to the `Info.plist` file for the iOS Hyperskill app. The change ensures that the app specifies a minimum system version requirement.
* [`iosHyperskillApp/iosHyperskillApp/Info.plist`](diffhunk://#diff-5f27f7839eefb94696173dfe041a93fd756db5bc180f577cd63030e10c334d21R44-R45): Added the `LSMinimumSystemVersion` key with a value of `12.0` to specify the minimum required iOS version for the app.
=> iOS: Specify LSMinimumSystemVersion value of 12.0

.github/workflows/android_beta_deployment.yml, .github/workflows/android_deploy_to_firebase.yml, .github/workflows/android_deploy_to_firebase_manually.yml, .github/workflows/android_release_deployment.yml, .github/workflows/auto_author_assign.yml, .github/workflows/build_caches.yml, .github/workflows/ci.yml, .github/workflows/cleanup_pr_caches.yml, .github/workflows/detect_changed_files_reusable_workflow.yml, .github/workflows/gh_pages_analytics.yml, .github/workflows/gpt_review.yml, .github/workflows/greetings.yml, .github/workflows/ios_beta_deployment.yml, .github/workflows/ios_release_deployment.yml, .github/workflows/label.yml, .github/workflows/merge_main_into_develop.yml, .github/workflows/stale.yml
Resolves #1212 
**Checklist**
This pull request updates the GitHub Actions workflows to use the latest Ubuntu runner version. The changes ensure that all workflows are running on `ubuntu-latest` instead of the previously specified `ubuntu-22.04`.
Updates to GitHub Actions workflows:
* [`.github/workflows/android_beta_deployment.yml`](diffhunk://#diff-191b109092f50bcc9872a21bacf3e6e51a33b15f3c83ed9861c8b617a3a0345eL25-R25): Updated `runs-on` to `ubuntu-latest` for `Gradle Wrapper Validation` and `Deploy to Google Play` jobs. [[1]](diffhunk://#diff-191b109092f50bcc9872a21bacf3e6e51a33b15f3c83ed9861c8b617a3a0345eL25-R25) [[2]](diffhunk://#diff-191b109092f50bcc9872a21bacf3e6e51a33b15f3c83ed9861c8b617a3a0345eL44-R44)
* …
=> GitHub Actions:  Upgrade GitHub Runner Image from ubuntu-22.04 to ubuntu-latest

.github/workflows/ci.yml, .github/workflows/ios_beta_deployment.yml, .github/workflows/ios_release_deployment.yml, .github/workflows/ios_unit_testing.yml
Resolves #1214 
**Checklist**
This pull request includes several updates to the CI/CD workflows for the `iosHyperskillApp` project. The changes primarily involve standardizing the use of double quotes for strings and adding steps to upload error logs if a failure occurs.
Standardization and Consistency:
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL6-R24): Changed single quotes to double quotes for string values in `on.push.branches`, `workflow_dispatch.inputs`, `jobs.setup-ruby.with`, `jobs.cache-pods.with`, `jobs.install-pods.run`, `jobs.run-swiftlint.run`, and `jobs.build.run` sections. [[1]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL6-R24) …
=> GitHub Actions: Upload iOS app error log on CI build failure

iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/Model/Analyze/CodePlaygroundManager.swift
Resolves #1226 
This pull request includes several changes to the `CodePlaygroundManager` class in the `iosHyperskillApp` project, focusing on improving the method for converting a position to a text range in a `UITextView` and updating the method calls accordingly.
* Renamed and refactored the `textRangeFrom` method to `textRange` to improve readability and return an optional `UITextRange` instead of a required one. (`iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/Model/Analyze/CodePlaygroundManager.swift`)
* Updated method calls to use the new `textRange` method name and handle the optional return type appropriately. (`iosHyperskillApp/iosHyperskillApp/Sources/Frameworks/CodeEditor/Model/Analyze/CodePlaygroundManager.swift`)
* Updated the call in …
=> iOS: Fix NSInvalidArgumentException: Required value was nil in CodePlaygroundManager.swift

.github/workflows/stale.yml
This pull request includes an update to the `.github/workflows/stale.yml` file to improve the handling of stale pull requests.
Changes to stale pull request handling:
* [`.github/workflows/stale.yml`](diffhunk://#diff-b5e0854ed0838024d5cc25b4e030922e34648b9ea8c432807e35495fb805b894R25): Added `exempt-pr-labels` to exclude certain labels from being marked as stale.
=> GitHub Actions: Add exempt-pr-labels for stale
